services:
  database:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - squad-aegis-database:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=squad-aegis
      - POSTGRES_USER=squad-aegis
      - POSTGRES_DB=squad-aegis
    networks:
      - default

volumes:
  squad-aegis-database:

networks:
  default:
    driver: bridge
