services:
  database:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=squad-aegis
      - POSTGRES_PASSWORD=squad-aegis
      - POSTGRES_DB=squad-aegis
      - POSTGRES_INITDB_ARGS=
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U squad-aegis"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  clickhouse:
    image: clickhouse/clickhouse-server:25.3
    ports:
      - 8123:8123
      - 9000:9000
    volumes:
      - clickhouse:/var/lib/clickhouse
    environment:
      CLICKHOUSE_USER: "squad_aegis"
      CLICKHOUSE_PASSWORD: "squad_aegis"
    healthcheck:
      test: ["CMD", "clickhouse-client", "--query", "SELECT 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  server:
    image: insidiousfiddler/squad-aegis:latest
    depends_on:
      - database
      - clickhouse
    ports:
      - 3113:80
    volumes:
      - data:/etc/squad-aegis
    env_file:
      - .env
    restart: unless-stopped

volumes:
  database:
  clickhouse:
  data:
