services:
  logwatcher:
    image: registry.vmgware.dev/insidiousfiddler/squad-aegis-logwatcher:latest
    ports:
      - 31135:31135
    volumes:
      - <path to log files>:/etc/squad-aegis/logwatcher/squad-game-logs
    environment:
      # Core configuration
      - LOGWATCHER_PORT=31135
      - LOGWATCHER_AUTH_TOKEN=<auth token>
      
      # Local file source configuration (default)
      - LOGWATCHER_SOURCE_TYPE=local
      - LOGWATCHER_LOG_FILE=/etc/squad-aegis/logwatcher/squad-game-logs/SquadGame.log
      
      # Behavior settings
      - LOGWATCHER_READ_FROM_START=false  # Set to true to read entire log file history
      
      # Remote file source configuration (uncomment and configure as needed)
      # For SFTP:
      # - LOGWATCHER_SOURCE_TYPE=sftp
      # - LOGWATCHER_HOST=<sftp server address>
      # - LOGWATCHER_REMOTE_PORT=22
      # - LOGWATCHER_USERNAME=<sftp username>
      # - LOGWATCHER_PASSWORD=<sftp password>
      # - LOGWATCHER_REMOTE_PATH=/path/to/SquadGame.log
      # - LOGWATCHER_POLL_FREQUENCY=5s
      
      # For FTP:
      # - LOGWATCHER_SOURCE_TYPE=ftp
      # - LOGWATCHER_HOST=<ftp server address>
      # - LOGWATCHER_REMOTE_PORT=21
      # - LOGWATCHER_USERNAME=<ftp username>
      # - LOGWATCHER_PASSWORD=<ftp password>
      # - LOGWATCHER_REMOTE_PATH=/path/to/SquadGame.log
      # - LOGWATCHER_POLL_FREQUENCY=5s
    networks:
      - default

networks:
  default:
    driver: bridge
