services:
  database:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - squad-aegis-database:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=squad-aegis
      - POSTGRES_USER=squad-aegis
      - POSTGRES_DB=squad-aegis
    networks:
      - default

  valkey:
    image: redis:7-alpine
    ports:
      - 6379:6379
    volumes:
      - valkey-data:/data
    networks:
      - default

  clickhouse-server:
    image: clickhouse/clickhouse-server:25.3
    ports:
      - 8123:8123
      - 9000:9000
    volumes:
      - clickhouse-data:/var/lib/clickhouse
    environment:
      CLICKHOUSE_USER: "squad_aegis"
      CLICKHOUSE_PASSWORD: "squad_aegis"
    networks:
      - default

  clickhouse-ui:
    image: ghcr.io/caioricciuti/ch-ui:latest
    ports:
      - "5521:5521"
    environment:
      VITE_CLICKHOUSE_URL: "http://127.0.0.1:8123"
      VITE_CLICKHOUSE_USER: "squad_aegis"
      VITE_CLICKHOUSE_PASS: "squad_aegis"
    networks:
      - default

volumes:
  squad-aegis-database:
  clickhouse-data:
  valkey-data:

networks:
  default:
    driver: bridge
