// HostAPI is the plugin-to-host service. The plugin subprocess dials the
// host on the broker ID supplied via Plugin.Initialize and then invokes
// methods on this service. All host-side authorization (rate limiting,
// payload caps, connector scope, Discord channel allowlist, etc.) lives in
// the host's implementation of this service.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: pkg/pluginrpc/proto/hostapi.proto

package pluginrpcpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// JSONResponse carries arbitrary JSON-encoded data. Used for replies whose
// shape is host-defined (player lists, server info, etc.).
type JSONResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DataJson      []byte                 `protobuf:"bytes,1,opt,name=data_json,json=dataJson,proto3" json:"data_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JSONResponse) Reset() {
	*x = JSONResponse{}
	mi := &file_pkg_pluginrpc_proto_hostapi_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JSONResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JSONResponse) ProtoMessage() {}

func (x *JSONResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pluginrpc_proto_hostapi_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JSONResponse.ProtoReflect.Descriptor instead.
func (*JSONResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pluginrpc_proto_hostapi_proto_rawDescGZIP(), []int{0}
}

func (x *JSONResponse) GetDataJson() []byte {
	if x != nil {
		return x.DataJson
	}
	return nil
}

type StringResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringResponse) Reset() {
	*x = StringResponse{}
	mi := &file_pkg_pluginrpc_proto_hostapi_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringResponse) ProtoMessage() {}

func (x *StringResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pluginrpc_proto_hostapi_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringResponse.ProtoReflect.Descriptor instead.
func (*StringResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pluginrpc_proto_hostapi_proto_rawDescGZIP(), []int{1}
}

func (x *StringResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type LogRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Message string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	// JSON-encoded fields map.
	FieldsJson    []byte `protobuf:"bytes,2,opt,name=fields_json,json=fieldsJson,proto3" json:"fields_json,omitempty"`
	Error         string `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogRequest) Reset() {
	*x = LogRequest{}
	mi := &file_pkg_pluginrpc_proto_hostapi_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogRequest) ProtoMessage() {}

func (x *LogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pluginrpc_proto_hostapi_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogRequest.ProtoReflect.Descriptor instead.
func (*LogRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pluginrpc_proto_hostapi_proto_rawDescGZIP(), []int{2}
}

func (x *LogRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LogRequest) GetFieldsJson() []byte {
	if x != nil {
		return x.FieldsJson
	}
	return nil
}

func (x *LogRequest) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type RconCommandRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Command       string                 `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RconCommandRequest) Reset() {
	*x = RconCommandRequest{}
	mi := &file_pkg_pluginrpc_proto_hostapi_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RconCommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RconCommandRequest) ProtoMessage() {}

func (x *RconCommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pluginrpc_proto_hostapi_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RconCommandRequest.ProtoReflect.Descriptor instead.
func (*RconCommandRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pluginrpc_proto_hostapi_proto_rawDescGZIP(), []int{3}
}

func (x *RconCommandRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

type RconCommandResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      string                 `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RconCommandResponse) Reset() {
	*x = RconCommandResponse{}
	mi := &file_pkg_pluginrpc_proto_hostapi_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RconCommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RconCommandResponse) ProtoMessage() {}

func (x *RconCommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pluginrpc_proto_hostapi_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RconCommandResponse.ProtoReflect.Descriptor instead.
func (*RconCommandResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pluginrpc_proto_hostapi_proto_rawDescGZIP(), []int{4}
}

func (x *RconCommandResponse) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

type RconBroadcastRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RconBroadcastRequest) Reset() {
	*x = RconBroadcastRequest{}
	mi := &file_pkg_pluginrpc_proto_hostapi_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RconBroadcastRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RconBroadcastRequest) ProtoMessage() {}

func (x *RconBroadcastRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pluginrpc_proto_hostapi_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RconBroadcastRequest.ProtoReflect.Descriptor instead.
func (*RconBroadcastRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pluginrpc_proto_hostapi_proto_rawDescGZIP(), []int{5}
}

func (x *RconBroadcastRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type RconWarnPlayerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RconWarnPlayerRequest) Reset() {
	*x = RconWarnPlayerRequest{}
	mi := &file_pkg_pluginrpc_proto_hostapi_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RconWarnPlayerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RconWarnPlayerRequest) ProtoMessage() {}

func (x *RconWarnPlayerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pluginrpc_proto_hostapi_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RconWarnPlayerRequest.ProtoReflect.Descriptor instead.
func (*RconWarnPlayerRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pluginrpc_proto_hostapi_proto_rawDescGZIP(), []int{6}
}

func (x *RconWarnPlayerRequest) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *RconWarnPlayerRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type RconKickRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RconKickRequest) Reset() {
	*x = RconKickRequest{}
	mi := &file_pkg_pluginrpc_proto_hostapi_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RconKickRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RconKickRequest) ProtoMessage() {}

func (x *RconKickRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pluginrpc_proto_hostapi_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RconKickRequest.ProtoReflect.Descriptor instead.
func (*RconKickRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pluginrpc_proto_hostapi_proto_rawDescGZIP(), []int{7}
}

func (x *RconKickRequest) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *RconKickRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type RconBanRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	PlayerId string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Reason   string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	// duration in nanoseconds (matches time.Duration).
	DurationNs int64  `protobuf:"varint,3,opt,name=duration_ns,json=durationNs,proto3" json:"duration_ns,omitempty"`
	EventId    string `protobuf:"bytes,4,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	EventType  string `protobuf:"bytes,5,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	// rule_id is optional. Empty string means nil.
	RuleId    string `protobuf:"bytes,6,opt,name=rule_id,json=ruleId,proto3" json:"rule_id,omitempty"`
	RuleIdSet bool   `protobuf:"varint,7,opt,name=rule_id_set,json=ruleIdSet,proto3" json:"rule_id_set,omitempty"`
	// JSON-encoded metadata map.
	MetadataJson  []byte `protobuf:"bytes,8,opt,name=metadata_json,json=metadataJson,proto3" json:"metadata_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RconBanRequest) Reset() {
	*x = RconBanRequest{}
	mi := &file_pkg_pluginrpc_proto_hostapi_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RconBanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RconBanRequest) ProtoMessage() {}

func (x *RconBanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pluginrpc_proto_hostapi_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RconBanRequest.ProtoReflect.Descriptor instead.
func (*RconBanRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pluginrpc_proto_hostapi_proto_rawDescGZIP(), []int{8}
}

func (x *RconBanRequest) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *RconBanRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *RconBanRequest) GetDurationNs() int64 {
	if x != nil {
		return x.DurationNs
	}
	return 0
}

func (x *RconBanRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *RconBanRequest) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *RconBanRequest) GetRuleId() string {
	if x != nil {
		return x.RuleId
	}
	return ""
}

func (x *RconBanRequest) GetRuleIdSet() bool {
	if x != nil {
		return x.RuleIdSet
	}
	return false
}

func (x *RconBanRequest) GetMetadataJson() []byte {
	if x != nil {
		return x.MetadataJson
	}
	return nil
}

type BanResultResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BanId         string                 `protobuf:"bytes,1,opt,name=ban_id,json=banId,proto3" json:"ban_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BanResultResponse) Reset() {
	*x = BanResultResponse{}
	mi := &file_pkg_pluginrpc_proto_hostapi_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BanResultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BanResultResponse) ProtoMessage() {}

func (x *BanResultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pluginrpc_proto_hostapi_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BanResultResponse.ProtoReflect.Descriptor instead.
func (*BanResultResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pluginrpc_proto_hostapi_proto_rawDescGZIP(), []int{9}
}

func (x *BanResultResponse) GetBanId() string {
	if x != nil {
		return x.BanId
	}
	return ""
}

type RconRemoveSquadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RconRemoveSquadRequest) Reset() {
	*x = RconRemoveSquadRequest{}
	mi := &file_pkg_pluginrpc_proto_hostapi_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RconRemoveSquadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RconRemoveSquadRequest) ProtoMessage() {}

func (x *RconRemoveSquadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pluginrpc_proto_hostapi_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RconRemoveSquadRequest.ProtoReflect.Descriptor instead.
func (*RconRemoveSquadRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pluginrpc_proto_hostapi_proto_rawDescGZIP(), []int{10}
}

func (x *RconRemoveSquadRequest) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

type DatabaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DatabaseRequest) Reset() {
	*x = DatabaseRequest{}
	mi := &file_pkg_pluginrpc_proto_hostapi_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DatabaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DatabaseRequest) ProtoMessage() {}

func (x *DatabaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pluginrpc_proto_hostapi_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DatabaseRequest.ProtoReflect.Descriptor instead.
func (*DatabaseRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pluginrpc_proto_hostapi_proto_rawDescGZIP(), []int{11}
}

func (x *DatabaseRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *DatabaseRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type DatabaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DatabaseResponse) Reset() {
	*x = DatabaseResponse{}
	mi := &file_pkg_pluginrpc_proto_hostapi_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DatabaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DatabaseResponse) ProtoMessage() {}

func (x *DatabaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pluginrpc_proto_hostapi_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DatabaseResponse.ProtoReflect.Descriptor instead.
func (*DatabaseResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pluginrpc_proto_hostapi_proto_rawDescGZIP(), []int{12}
}

func (x *DatabaseResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type ListRulesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// parent_rule_id is optional; empty string + parent_rule_id_set=false means nil.
	ParentRuleId    string `protobuf:"bytes,1,opt,name=parent_rule_id,json=parentRuleId,proto3" json:"parent_rule_id,omitempty"`
	ParentRuleIdSet bool   `protobuf:"varint,2,opt,name=parent_rule_id_set,json=parentRuleIdSet,proto3" json:"parent_rule_id_set,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ListRulesRequest) Reset() {
	*x = ListRulesRequest{}
	mi := &file_pkg_pluginrpc_proto_hostapi_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRulesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRulesRequest) ProtoMessage() {}

func (x *ListRulesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pluginrpc_proto_hostapi_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRulesRequest.ProtoReflect.Descriptor instead.
func (*ListRulesRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pluginrpc_proto_hostapi_proto_rawDescGZIP(), []int{13}
}

func (x *ListRulesRequest) GetParentRuleId() string {
	if x != nil {
		return x.ParentRuleId
	}
	return ""
}

func (x *ListRulesRequest) GetParentRuleIdSet() bool {
	if x != nil {
		return x.ParentRuleIdSet
	}
	return false
}

type ListRuleActionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RuleId        string                 `protobuf:"bytes,1,opt,name=rule_id,json=ruleId,proto3" json:"rule_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRuleActionsRequest) Reset() {
	*x = ListRuleActionsRequest{}
	mi := &file_pkg_pluginrpc_proto_hostapi_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRuleActionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRuleActionsRequest) ProtoMessage() {}

func (x *ListRuleActionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pluginrpc_proto_hostapi_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRuleActionsRequest.ProtoReflect.Descriptor instead.
func (*ListRuleActionsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pluginrpc_proto_hostapi_proto_rawDescGZIP(), []int{14}
}

func (x *ListRuleActionsRequest) GetRuleId() string {
	if x != nil {
		return x.RuleId
	}
	return ""
}

type AddTempAdminRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	PlayerId string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	RoleName string                 `protobuf:"bytes,2,opt,name=role_name,json=roleName,proto3" json:"role_name,omitempty"`
	Notes    string                 `protobuf:"bytes,3,opt,name=notes,proto3" json:"notes,omitempty"`
	// expires_at unset means nil.
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddTempAdminRequest) Reset() {
	*x = AddTempAdminRequest{}
	mi := &file_pkg_pluginrpc_proto_hostapi_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddTempAdminRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddTempAdminRequest) ProtoMessage() {}

func (x *AddTempAdminRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pluginrpc_proto_hostapi_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddTempAdminRequest.ProtoReflect.Descriptor instead.
func (*AddTempAdminRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pluginrpc_proto_hostapi_proto_rawDescGZIP(), []int{15}
}

func (x *AddTempAdminRequest) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *AddTempAdminRequest) GetRoleName() string {
	if x != nil {
		return x.RoleName
	}
	return ""
}

func (x *AddTempAdminRequest) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

func (x *AddTempAdminRequest) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

type RemoveTempAdminRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	RoleName      string                 `protobuf:"bytes,2,opt,name=role_name,json=roleName,proto3" json:"role_name,omitempty"`
	Notes         string                 `protobuf:"bytes,3,opt,name=notes,proto3" json:"notes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveTempAdminRequest) Reset() {
	*x = RemoveTempAdminRequest{}
	mi := &file_pkg_pluginrpc_proto_hostapi_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveTempAdminRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveTempAdminRequest) ProtoMessage() {}

func (x *RemoveTempAdminRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pluginrpc_proto_hostapi_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveTempAdminRequest.ProtoReflect.Descriptor instead.
func (*RemoveTempAdminRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pluginrpc_proto_hostapi_proto_rawDescGZIP(), []int{16}
}

func (x *RemoveTempAdminRequest) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *RemoveTempAdminRequest) GetRoleName() string {
	if x != nil {
		return x.RoleName
	}
	return ""
}

func (x *RemoveTempAdminRequest) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

type PlayerIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerIDRequest) Reset() {
	*x = PlayerIDRequest{}
	mi := &file_pkg_pluginrpc_proto_hostapi_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerIDRequest) ProtoMessage() {}

func (x *PlayerIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pluginrpc_proto_hostapi_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerIDRequest.ProtoReflect.Descriptor instead.
func (*PlayerIDRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pluginrpc_proto_hostapi_proto_rawDescGZIP(), []int{17}
}

func (x *PlayerIDRequest) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

type PublishEventRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	EventType string                 `protobuf:"bytes,1,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	// JSON-encoded data map.
	DataJson      []byte `protobuf:"bytes,2,opt,name=data_json,json=dataJson,proto3" json:"data_json,omitempty"`
	Raw           string `protobuf:"bytes,3,opt,name=raw,proto3" json:"raw,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishEventRequest) Reset() {
	*x = PublishEventRequest{}
	mi := &file_pkg_pluginrpc_proto_hostapi_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishEventRequest) ProtoMessage() {}

func (x *PublishEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pluginrpc_proto_hostapi_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishEventRequest.ProtoReflect.Descriptor instead.
func (*PublishEventRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pluginrpc_proto_hostapi_proto_rawDescGZIP(), []int{18}
}

func (x *PublishEventRequest) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *PublishEventRequest) GetDataJson() []byte {
	if x != nil {
		return x.DataJson
	}
	return nil
}

func (x *PublishEventRequest) GetRaw() string {
	if x != nil {
		return x.Raw
	}
	return ""
}

type DiscordMessageRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	ChannelId string                 `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	Content   string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	// JSON-encoded embed map.
	EmbedJson     []byte `protobuf:"bytes,3,opt,name=embed_json,json=embedJson,proto3" json:"embed_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiscordMessageRequest) Reset() {
	*x = DiscordMessageRequest{}
	mi := &file_pkg_pluginrpc_proto_hostapi_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscordMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscordMessageRequest) ProtoMessage() {}

func (x *DiscordMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pluginrpc_proto_hostapi_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscordMessageRequest.ProtoReflect.Descriptor instead.
func (*DiscordMessageRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pluginrpc_proto_hostapi_proto_rawDescGZIP(), []int{19}
}

func (x *DiscordMessageRequest) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *DiscordMessageRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *DiscordMessageRequest) GetEmbedJson() []byte {
	if x != nil {
		return x.EmbedJson
	}
	return nil
}

type DiscordMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiscordMessageResponse) Reset() {
	*x = DiscordMessageResponse{}
	mi := &file_pkg_pluginrpc_proto_hostapi_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscordMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscordMessageResponse) ProtoMessage() {}

func (x *DiscordMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pluginrpc_proto_hostapi_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscordMessageResponse.ProtoReflect.Descriptor instead.
func (*DiscordMessageResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pluginrpc_proto_hostapi_proto_rawDescGZIP(), []int{20}
}

func (x *DiscordMessageResponse) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

type ConnectorCallRequest struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	ConnectorId string                 `protobuf:"bytes,1,opt,name=connector_id,json=connectorId,proto3" json:"connector_id,omitempty"`
	V           string                 `protobuf:"bytes,2,opt,name=v,proto3" json:"v,omitempty"`
	// JSON-encoded data map.
	DataJson      []byte `protobuf:"bytes,3,opt,name=data_json,json=dataJson,proto3" json:"data_json,omitempty"`
	TimeoutMs     int64  `protobuf:"varint,4,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectorCallRequest) Reset() {
	*x = ConnectorCallRequest{}
	mi := &file_pkg_pluginrpc_proto_hostapi_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectorCallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectorCallRequest) ProtoMessage() {}

func (x *ConnectorCallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pluginrpc_proto_hostapi_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectorCallRequest.ProtoReflect.Descriptor instead.
func (*ConnectorCallRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pluginrpc_proto_hostapi_proto_rawDescGZIP(), []int{21}
}

func (x *ConnectorCallRequest) GetConnectorId() string {
	if x != nil {
		return x.ConnectorId
	}
	return ""
}

func (x *ConnectorCallRequest) GetV() string {
	if x != nil {
		return x.V
	}
	return ""
}

func (x *ConnectorCallRequest) GetDataJson() []byte {
	if x != nil {
		return x.DataJson
	}
	return nil
}

func (x *ConnectorCallRequest) GetTimeoutMs() int64 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

type ConnectorCallResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	V     string                 `protobuf:"bytes,1,opt,name=v,proto3" json:"v,omitempty"`
	Ok    bool                   `protobuf:"varint,2,opt,name=ok,proto3" json:"ok,omitempty"`
	// JSON-encoded data map.
	DataJson      []byte `protobuf:"bytes,3,opt,name=data_json,json=dataJson,proto3" json:"data_json,omitempty"`
	Error         string `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectorCallResponse) Reset() {
	*x = ConnectorCallResponse{}
	mi := &file_pkg_pluginrpc_proto_hostapi_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectorCallResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectorCallResponse) ProtoMessage() {}

func (x *ConnectorCallResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pluginrpc_proto_hostapi_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectorCallResponse.ProtoReflect.Descriptor instead.
func (*ConnectorCallResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pluginrpc_proto_hostapi_proto_rawDescGZIP(), []int{22}
}

func (x *ConnectorCallResponse) GetV() string {
	if x != nil {
		return x.V
	}
	return ""
}

func (x *ConnectorCallResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *ConnectorCallResponse) GetDataJson() []byte {
	if x != nil {
		return x.DataJson
	}
	return nil
}

func (x *ConnectorCallResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_pkg_pluginrpc_proto_hostapi_proto protoreflect.FileDescriptor

const file_pkg_pluginrpc_proto_hostapi_proto_rawDesc = "" +
	"\n" +
	"!pkg/pluginrpc/proto/hostapi.proto\x12\x17squadaegis.pluginrpc.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a pkg/pluginrpc/proto/plugin.proto\"+\n" +
	"\fJSONResponse\x12\x1b\n" +
	"\tdata_json\x18\x01 \x01(\fR\bdataJson\"&\n" +
	"\x0eStringResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\"]\n" +
	"\n" +
	"LogRequest\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x1f\n" +
	"\vfields_json\x18\x02 \x01(\fR\n" +
	"fieldsJson\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\".\n" +
	"\x12RconCommandRequest\x12\x18\n" +
	"\acommand\x18\x01 \x01(\tR\acommand\"1\n" +
	"\x13RconCommandResponse\x12\x1a\n" +
	"\bresponse\x18\x01 \x01(\tR\bresponse\"0\n" +
	"\x14RconBroadcastRequest\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"N\n" +
	"\x15RconWarnPlayerRequest\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"F\n" +
	"\x0fRconKickRequest\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"\xfe\x01\n" +
	"\x0eRconBanRequest\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12\x1f\n" +
	"\vduration_ns\x18\x03 \x01(\x03R\n" +
	"durationNs\x12\x19\n" +
	"\bevent_id\x18\x04 \x01(\tR\aeventId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x05 \x01(\tR\teventType\x12\x17\n" +
	"\arule_id\x18\x06 \x01(\tR\x06ruleId\x12\x1e\n" +
	"\vrule_id_set\x18\a \x01(\bR\truleIdSet\x12#\n" +
	"\rmetadata_json\x18\b \x01(\fR\fmetadataJson\"*\n" +
	"\x11BanResultResponse\x12\x15\n" +
	"\x06ban_id\x18\x01 \x01(\tR\x05banId\"5\n" +
	"\x16RconRemoveSquadRequest\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\"9\n" +
	"\x0fDatabaseRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"(\n" +
	"\x10DatabaseResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\"e\n" +
	"\x10ListRulesRequest\x12$\n" +
	"\x0eparent_rule_id\x18\x01 \x01(\tR\fparentRuleId\x12+\n" +
	"\x12parent_rule_id_set\x18\x02 \x01(\bR\x0fparentRuleIdSet\"1\n" +
	"\x16ListRuleActionsRequest\x12\x17\n" +
	"\arule_id\x18\x01 \x01(\tR\x06ruleId\"\xa0\x01\n" +
	"\x13AddTempAdminRequest\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\x1b\n" +
	"\trole_name\x18\x02 \x01(\tR\broleName\x12\x14\n" +
	"\x05notes\x18\x03 \x01(\tR\x05notes\x129\n" +
	"\n" +
	"expires_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"h\n" +
	"\x16RemoveTempAdminRequest\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\x1b\n" +
	"\trole_name\x18\x02 \x01(\tR\broleName\x12\x14\n" +
	"\x05notes\x18\x03 \x01(\tR\x05notes\".\n" +
	"\x0fPlayerIDRequest\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\"c\n" +
	"\x13PublishEventRequest\x12\x1d\n" +
	"\n" +
	"event_type\x18\x01 \x01(\tR\teventType\x12\x1b\n" +
	"\tdata_json\x18\x02 \x01(\fR\bdataJson\x12\x10\n" +
	"\x03raw\x18\x03 \x01(\tR\x03raw\"o\n" +
	"\x15DiscordMessageRequest\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\tR\tchannelId\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x1d\n" +
	"\n" +
	"embed_json\x18\x03 \x01(\fR\tembedJson\"7\n" +
	"\x16DiscordMessageResponse\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\"\x83\x01\n" +
	"\x14ConnectorCallRequest\x12!\n" +
	"\fconnector_id\x18\x01 \x01(\tR\vconnectorId\x12\f\n" +
	"\x01v\x18\x02 \x01(\tR\x01v\x12\x1b\n" +
	"\tdata_json\x18\x03 \x01(\fR\bdataJson\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x04 \x01(\x03R\ttimeoutMs\"h\n" +
	"\x15ConnectorCallResponse\x12\f\n" +
	"\x01v\x18\x01 \x01(\tR\x01v\x12\x0e\n" +
	"\x02ok\x18\x02 \x01(\bR\x02ok\x12\x1b\n" +
	"\tdata_json\x18\x03 \x01(\fR\bdataJson\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error2\xd7\x1c\n" +
	"\aHostAPI\x12N\n" +
	"\aLogInfo\x12#.squadaegis.pluginrpc.v1.LogRequest\x1a\x1e.squadaegis.pluginrpc.v1.Empty\x12N\n" +
	"\aLogWarn\x12#.squadaegis.pluginrpc.v1.LogRequest\x1a\x1e.squadaegis.pluginrpc.v1.Empty\x12O\n" +
	"\bLogError\x12#.squadaegis.pluginrpc.v1.LogRequest\x1a\x1e.squadaegis.pluginrpc.v1.Empty\x12O\n" +
	"\bLogDebug\x12#.squadaegis.pluginrpc.v1.LogRequest\x1a\x1e.squadaegis.pluginrpc.v1.Empty\x12l\n" +
	"\x0fRconSendCommand\x12+.squadaegis.pluginrpc.v1.RconCommandRequest\x1a,.squadaegis.pluginrpc.v1.RconCommandResponse\x12^\n" +
	"\rRconBroadcast\x12-.squadaegis.pluginrpc.v1.RconBroadcastRequest\x1a\x1e.squadaegis.pluginrpc.v1.Empty\x12i\n" +
	"\x17RconSendWarningToPlayer\x12..squadaegis.pluginrpc.v1.RconWarnPlayerRequest\x1a\x1e.squadaegis.pluginrpc.v1.Empty\x12Z\n" +
	"\x0eRconKickPlayer\x12(.squadaegis.pluginrpc.v1.RconKickRequest\x1a\x1e.squadaegis.pluginrpc.v1.Empty\x12X\n" +
	"\rRconBanPlayer\x12'.squadaegis.pluginrpc.v1.RconBanRequest\x1a\x1e.squadaegis.pluginrpc.v1.Empty\x12j\n" +
	"\x13RconBanWithEvidence\x12'.squadaegis.pluginrpc.v1.RconBanRequest\x1a*.squadaegis.pluginrpc.v1.BanResultResponse\x12a\n" +
	"\x16RconWarnPlayerWithRule\x12'.squadaegis.pluginrpc.v1.RconBanRequest\x1a\x1e.squadaegis.pluginrpc.v1.Empty\x12a\n" +
	"\x16RconKickPlayerWithRule\x12'.squadaegis.pluginrpc.v1.RconBanRequest\x1a\x1e.squadaegis.pluginrpc.v1.Empty\x12`\n" +
	"\x15RconBanPlayerWithRule\x12'.squadaegis.pluginrpc.v1.RconBanRequest\x1a\x1e.squadaegis.pluginrpc.v1.Empty\x12q\n" +
	"\x1aRconBanWithEvidenceAndRule\x12'.squadaegis.pluginrpc.v1.RconBanRequest\x1a*.squadaegis.pluginrpc.v1.BanResultResponse\x12|\n" +
	"%RconBanWithEvidenceAndRuleAndMetadata\x12'.squadaegis.pluginrpc.v1.RconBanRequest\x1a*.squadaegis.pluginrpc.v1.BanResultResponse\x12l\n" +
	"\x19RconRemovePlayerFromSquad\x12/.squadaegis.pluginrpc.v1.RconRemoveSquadRequest\x1a\x1e.squadaegis.pluginrpc.v1.Empty\x12p\n" +
	"\x1dRconRemovePlayerFromSquadById\x12/.squadaegis.pluginrpc.v1.RconRemoveSquadRequest\x1a\x1e.squadaegis.pluginrpc.v1.Empty\x12\\\n" +
	"\x11ServerGetServerID\x12\x1e.squadaegis.pluginrpc.v1.Empty\x1a'.squadaegis.pluginrpc.v1.StringResponse\x12\\\n" +
	"\x13ServerGetServerInfo\x12\x1e.squadaegis.pluginrpc.v1.Empty\x1a%.squadaegis.pluginrpc.v1.JSONResponse\x12Y\n" +
	"\x10ServerGetPlayers\x12\x1e.squadaegis.pluginrpc.v1.Empty\x1a%.squadaegis.pluginrpc.v1.JSONResponse\x12X\n" +
	"\x0fServerGetAdmins\x12\x1e.squadaegis.pluginrpc.v1.Empty\x1a%.squadaegis.pluginrpc.v1.JSONResponse\x12X\n" +
	"\x0fServerGetSquads\x12\x1e.squadaegis.pluginrpc.v1.Empty\x1a%.squadaegis.pluginrpc.v1.JSONResponse\x12l\n" +
	"\x15DatabaseGetPluginData\x12(.squadaegis.pluginrpc.v1.DatabaseRequest\x1a).squadaegis.pluginrpc.v1.DatabaseResponse\x12a\n" +
	"\x15DatabaseSetPluginData\x12(.squadaegis.pluginrpc.v1.DatabaseRequest\x1a\x1e.squadaegis.pluginrpc.v1.Empty\x12d\n" +
	"\x18DatabaseDeletePluginData\x12(.squadaegis.pluginrpc.v1.DatabaseRequest\x1a\x1e.squadaegis.pluginrpc.v1.Empty\x12g\n" +
	"\x13RuleListServerRules\x12).squadaegis.pluginrpc.v1.ListRulesRequest\x1a%.squadaegis.pluginrpc.v1.JSONResponse\x12s\n" +
	"\x19RuleListServerRuleActions\x12/.squadaegis.pluginrpc.v1.ListRuleActionsRequest\x1a%.squadaegis.pluginrpc.v1.JSONResponse\x12f\n" +
	"\x16AdminAddTemporaryAdmin\x12,.squadaegis.pluginrpc.v1.AddTempAdminRequest\x1a\x1e.squadaegis.pluginrpc.v1.Empty\x12l\n" +
	"\x19AdminRemoveTemporaryAdmin\x12/.squadaegis.pluginrpc.v1.RemoveTempAdminRequest\x1a\x1e.squadaegis.pluginrpc.v1.Empty\x12p\n" +
	"\x1dAdminRemoveTemporaryAdminRole\x12/.squadaegis.pluginrpc.v1.RemoveTempAdminRequest\x1a\x1e.squadaegis.pluginrpc.v1.Empty\x12l\n" +
	"\x19AdminGetPlayerAdminStatus\x12(.squadaegis.pluginrpc.v1.PlayerIDRequest\x1a%.squadaegis.pluginrpc.v1.JSONResponse\x12a\n" +
	"\x18AdminListTemporaryAdmins\x12\x1e.squadaegis.pluginrpc.v1.Empty\x1a%.squadaegis.pluginrpc.v1.JSONResponse\x12a\n" +
	"\x11EventPublishEvent\x12,.squadaegis.pluginrpc.v1.PublishEventRequest\x1a\x1e.squadaegis.pluginrpc.v1.Empty\x12u\n" +
	"\x12DiscordSendMessage\x12..squadaegis.pluginrpc.v1.DiscordMessageRequest\x1a/.squadaegis.pluginrpc.v1.DiscordMessageResponse\x12s\n" +
	"\x10DiscordSendEmbed\x12..squadaegis.pluginrpc.v1.DiscordMessageRequest\x1a/.squadaegis.pluginrpc.v1.DiscordMessageResponse\x12n\n" +
	"\rConnectorCall\x12-.squadaegis.pluginrpc.v1.ConnectorCallRequest\x1a..squadaegis.pluginrpc.v1.ConnectorCallResponseB?Z=go.codycody31.dev/squad-aegis/pkg/pluginrpc/proto;pluginrpcpbb\x06proto3"

var (
	file_pkg_pluginrpc_proto_hostapi_proto_rawDescOnce sync.Once
	file_pkg_pluginrpc_proto_hostapi_proto_rawDescData []byte
)

func file_pkg_pluginrpc_proto_hostapi_proto_rawDescGZIP() []byte {
	file_pkg_pluginrpc_proto_hostapi_proto_rawDescOnce.Do(func() {
		file_pkg_pluginrpc_proto_hostapi_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_pluginrpc_proto_hostapi_proto_rawDesc), len(file_pkg_pluginrpc_proto_hostapi_proto_rawDesc)))
	})
	return file_pkg_pluginrpc_proto_hostapi_proto_rawDescData
}

var file_pkg_pluginrpc_proto_hostapi_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_pkg_pluginrpc_proto_hostapi_proto_goTypes = []any{
	(*JSONResponse)(nil),           // 0: squadaegis.pluginrpc.v1.JSONResponse
	(*StringResponse)(nil),         // 1: squadaegis.pluginrpc.v1.StringResponse
	(*LogRequest)(nil),             // 2: squadaegis.pluginrpc.v1.LogRequest
	(*RconCommandRequest)(nil),     // 3: squadaegis.pluginrpc.v1.RconCommandRequest
	(*RconCommandResponse)(nil),    // 4: squadaegis.pluginrpc.v1.RconCommandResponse
	(*RconBroadcastRequest)(nil),   // 5: squadaegis.pluginrpc.v1.RconBroadcastRequest
	(*RconWarnPlayerRequest)(nil),  // 6: squadaegis.pluginrpc.v1.RconWarnPlayerRequest
	(*RconKickRequest)(nil),        // 7: squadaegis.pluginrpc.v1.RconKickRequest
	(*RconBanRequest)(nil),         // 8: squadaegis.pluginrpc.v1.RconBanRequest
	(*BanResultResponse)(nil),      // 9: squadaegis.pluginrpc.v1.BanResultResponse
	(*RconRemoveSquadRequest)(nil), // 10: squadaegis.pluginrpc.v1.RconRemoveSquadRequest
	(*DatabaseRequest)(nil),        // 11: squadaegis.pluginrpc.v1.DatabaseRequest
	(*DatabaseResponse)(nil),       // 12: squadaegis.pluginrpc.v1.DatabaseResponse
	(*ListRulesRequest)(nil),       // 13: squadaegis.pluginrpc.v1.ListRulesRequest
	(*ListRuleActionsRequest)(nil), // 14: squadaegis.pluginrpc.v1.ListRuleActionsRequest
	(*AddTempAdminRequest)(nil),    // 15: squadaegis.pluginrpc.v1.AddTempAdminRequest
	(*RemoveTempAdminRequest)(nil), // 16: squadaegis.pluginrpc.v1.RemoveTempAdminRequest
	(*PlayerIDRequest)(nil),        // 17: squadaegis.pluginrpc.v1.PlayerIDRequest
	(*PublishEventRequest)(nil),    // 18: squadaegis.pluginrpc.v1.PublishEventRequest
	(*DiscordMessageRequest)(nil),  // 19: squadaegis.pluginrpc.v1.DiscordMessageRequest
	(*DiscordMessageResponse)(nil), // 20: squadaegis.pluginrpc.v1.DiscordMessageResponse
	(*ConnectorCallRequest)(nil),   // 21: squadaegis.pluginrpc.v1.ConnectorCallRequest
	(*ConnectorCallResponse)(nil),  // 22: squadaegis.pluginrpc.v1.ConnectorCallResponse
	(*timestamppb.Timestamp)(nil),  // 23: google.protobuf.Timestamp
	(*Empty)(nil),                  // 24: squadaegis.pluginrpc.v1.Empty
}
var file_pkg_pluginrpc_proto_hostapi_proto_depIdxs = []int32{
	23, // 0: squadaegis.pluginrpc.v1.AddTempAdminRequest.expires_at:type_name -> google.protobuf.Timestamp
	2,  // 1: squadaegis.pluginrpc.v1.HostAPI.LogInfo:input_type -> squadaegis.pluginrpc.v1.LogRequest
	2,  // 2: squadaegis.pluginrpc.v1.HostAPI.LogWarn:input_type -> squadaegis.pluginrpc.v1.LogRequest
	2,  // 3: squadaegis.pluginrpc.v1.HostAPI.LogError:input_type -> squadaegis.pluginrpc.v1.LogRequest
	2,  // 4: squadaegis.pluginrpc.v1.HostAPI.LogDebug:input_type -> squadaegis.pluginrpc.v1.LogRequest
	3,  // 5: squadaegis.pluginrpc.v1.HostAPI.RconSendCommand:input_type -> squadaegis.pluginrpc.v1.RconCommandRequest
	5,  // 6: squadaegis.pluginrpc.v1.HostAPI.RconBroadcast:input_type -> squadaegis.pluginrpc.v1.RconBroadcastRequest
	6,  // 7: squadaegis.pluginrpc.v1.HostAPI.RconSendWarningToPlayer:input_type -> squadaegis.pluginrpc.v1.RconWarnPlayerRequest
	7,  // 8: squadaegis.pluginrpc.v1.HostAPI.RconKickPlayer:input_type -> squadaegis.pluginrpc.v1.RconKickRequest
	8,  // 9: squadaegis.pluginrpc.v1.HostAPI.RconBanPlayer:input_type -> squadaegis.pluginrpc.v1.RconBanRequest
	8,  // 10: squadaegis.pluginrpc.v1.HostAPI.RconBanWithEvidence:input_type -> squadaegis.pluginrpc.v1.RconBanRequest
	8,  // 11: squadaegis.pluginrpc.v1.HostAPI.RconWarnPlayerWithRule:input_type -> squadaegis.pluginrpc.v1.RconBanRequest
	8,  // 12: squadaegis.pluginrpc.v1.HostAPI.RconKickPlayerWithRule:input_type -> squadaegis.pluginrpc.v1.RconBanRequest
	8,  // 13: squadaegis.pluginrpc.v1.HostAPI.RconBanPlayerWithRule:input_type -> squadaegis.pluginrpc.v1.RconBanRequest
	8,  // 14: squadaegis.pluginrpc.v1.HostAPI.RconBanWithEvidenceAndRule:input_type -> squadaegis.pluginrpc.v1.RconBanRequest
	8,  // 15: squadaegis.pluginrpc.v1.HostAPI.RconBanWithEvidenceAndRuleAndMetadata:input_type -> squadaegis.pluginrpc.v1.RconBanRequest
	10, // 16: squadaegis.pluginrpc.v1.HostAPI.RconRemovePlayerFromSquad:input_type -> squadaegis.pluginrpc.v1.RconRemoveSquadRequest
	10, // 17: squadaegis.pluginrpc.v1.HostAPI.RconRemovePlayerFromSquadById:input_type -> squadaegis.pluginrpc.v1.RconRemoveSquadRequest
	24, // 18: squadaegis.pluginrpc.v1.HostAPI.ServerGetServerID:input_type -> squadaegis.pluginrpc.v1.Empty
	24, // 19: squadaegis.pluginrpc.v1.HostAPI.ServerGetServerInfo:input_type -> squadaegis.pluginrpc.v1.Empty
	24, // 20: squadaegis.pluginrpc.v1.HostAPI.ServerGetPlayers:input_type -> squadaegis.pluginrpc.v1.Empty
	24, // 21: squadaegis.pluginrpc.v1.HostAPI.ServerGetAdmins:input_type -> squadaegis.pluginrpc.v1.Empty
	24, // 22: squadaegis.pluginrpc.v1.HostAPI.ServerGetSquads:input_type -> squadaegis.pluginrpc.v1.Empty
	11, // 23: squadaegis.pluginrpc.v1.HostAPI.DatabaseGetPluginData:input_type -> squadaegis.pluginrpc.v1.DatabaseRequest
	11, // 24: squadaegis.pluginrpc.v1.HostAPI.DatabaseSetPluginData:input_type -> squadaegis.pluginrpc.v1.DatabaseRequest
	11, // 25: squadaegis.pluginrpc.v1.HostAPI.DatabaseDeletePluginData:input_type -> squadaegis.pluginrpc.v1.DatabaseRequest
	13, // 26: squadaegis.pluginrpc.v1.HostAPI.RuleListServerRules:input_type -> squadaegis.pluginrpc.v1.ListRulesRequest
	14, // 27: squadaegis.pluginrpc.v1.HostAPI.RuleListServerRuleActions:input_type -> squadaegis.pluginrpc.v1.ListRuleActionsRequest
	15, // 28: squadaegis.pluginrpc.v1.HostAPI.AdminAddTemporaryAdmin:input_type -> squadaegis.pluginrpc.v1.AddTempAdminRequest
	16, // 29: squadaegis.pluginrpc.v1.HostAPI.AdminRemoveTemporaryAdmin:input_type -> squadaegis.pluginrpc.v1.RemoveTempAdminRequest
	16, // 30: squadaegis.pluginrpc.v1.HostAPI.AdminRemoveTemporaryAdminRole:input_type -> squadaegis.pluginrpc.v1.RemoveTempAdminRequest
	17, // 31: squadaegis.pluginrpc.v1.HostAPI.AdminGetPlayerAdminStatus:input_type -> squadaegis.pluginrpc.v1.PlayerIDRequest
	24, // 32: squadaegis.pluginrpc.v1.HostAPI.AdminListTemporaryAdmins:input_type -> squadaegis.pluginrpc.v1.Empty
	18, // 33: squadaegis.pluginrpc.v1.HostAPI.EventPublishEvent:input_type -> squadaegis.pluginrpc.v1.PublishEventRequest
	19, // 34: squadaegis.pluginrpc.v1.HostAPI.DiscordSendMessage:input_type -> squadaegis.pluginrpc.v1.DiscordMessageRequest
	19, // 35: squadaegis.pluginrpc.v1.HostAPI.DiscordSendEmbed:input_type -> squadaegis.pluginrpc.v1.DiscordMessageRequest
	21, // 36: squadaegis.pluginrpc.v1.HostAPI.ConnectorCall:input_type -> squadaegis.pluginrpc.v1.ConnectorCallRequest
	24, // 37: squadaegis.pluginrpc.v1.HostAPI.LogInfo:output_type -> squadaegis.pluginrpc.v1.Empty
	24, // 38: squadaegis.pluginrpc.v1.HostAPI.LogWarn:output_type -> squadaegis.pluginrpc.v1.Empty
	24, // 39: squadaegis.pluginrpc.v1.HostAPI.LogError:output_type -> squadaegis.pluginrpc.v1.Empty
	24, // 40: squadaegis.pluginrpc.v1.HostAPI.LogDebug:output_type -> squadaegis.pluginrpc.v1.Empty
	4,  // 41: squadaegis.pluginrpc.v1.HostAPI.RconSendCommand:output_type -> squadaegis.pluginrpc.v1.RconCommandResponse
	24, // 42: squadaegis.pluginrpc.v1.HostAPI.RconBroadcast:output_type -> squadaegis.pluginrpc.v1.Empty
	24, // 43: squadaegis.pluginrpc.v1.HostAPI.RconSendWarningToPlayer:output_type -> squadaegis.pluginrpc.v1.Empty
	24, // 44: squadaegis.pluginrpc.v1.HostAPI.RconKickPlayer:output_type -> squadaegis.pluginrpc.v1.Empty
	24, // 45: squadaegis.pluginrpc.v1.HostAPI.RconBanPlayer:output_type -> squadaegis.pluginrpc.v1.Empty
	9,  // 46: squadaegis.pluginrpc.v1.HostAPI.RconBanWithEvidence:output_type -> squadaegis.pluginrpc.v1.BanResultResponse
	24, // 47: squadaegis.pluginrpc.v1.HostAPI.RconWarnPlayerWithRule:output_type -> squadaegis.pluginrpc.v1.Empty
	24, // 48: squadaegis.pluginrpc.v1.HostAPI.RconKickPlayerWithRule:output_type -> squadaegis.pluginrpc.v1.Empty
	24, // 49: squadaegis.pluginrpc.v1.HostAPI.RconBanPlayerWithRule:output_type -> squadaegis.pluginrpc.v1.Empty
	9,  // 50: squadaegis.pluginrpc.v1.HostAPI.RconBanWithEvidenceAndRule:output_type -> squadaegis.pluginrpc.v1.BanResultResponse
	9,  // 51: squadaegis.pluginrpc.v1.HostAPI.RconBanWithEvidenceAndRuleAndMetadata:output_type -> squadaegis.pluginrpc.v1.BanResultResponse
	24, // 52: squadaegis.pluginrpc.v1.HostAPI.RconRemovePlayerFromSquad:output_type -> squadaegis.pluginrpc.v1.Empty
	24, // 53: squadaegis.pluginrpc.v1.HostAPI.RconRemovePlayerFromSquadById:output_type -> squadaegis.pluginrpc.v1.Empty
	1,  // 54: squadaegis.pluginrpc.v1.HostAPI.ServerGetServerID:output_type -> squadaegis.pluginrpc.v1.StringResponse
	0,  // 55: squadaegis.pluginrpc.v1.HostAPI.ServerGetServerInfo:output_type -> squadaegis.pluginrpc.v1.JSONResponse
	0,  // 56: squadaegis.pluginrpc.v1.HostAPI.ServerGetPlayers:output_type -> squadaegis.pluginrpc.v1.JSONResponse
	0,  // 57: squadaegis.pluginrpc.v1.HostAPI.ServerGetAdmins:output_type -> squadaegis.pluginrpc.v1.JSONResponse
	0,  // 58: squadaegis.pluginrpc.v1.HostAPI.ServerGetSquads:output_type -> squadaegis.pluginrpc.v1.JSONResponse
	12, // 59: squadaegis.pluginrpc.v1.HostAPI.DatabaseGetPluginData:output_type -> squadaegis.pluginrpc.v1.DatabaseResponse
	24, // 60: squadaegis.pluginrpc.v1.HostAPI.DatabaseSetPluginData:output_type -> squadaegis.pluginrpc.v1.Empty
	24, // 61: squadaegis.pluginrpc.v1.HostAPI.DatabaseDeletePluginData:output_type -> squadaegis.pluginrpc.v1.Empty
	0,  // 62: squadaegis.pluginrpc.v1.HostAPI.RuleListServerRules:output_type -> squadaegis.pluginrpc.v1.JSONResponse
	0,  // 63: squadaegis.pluginrpc.v1.HostAPI.RuleListServerRuleActions:output_type -> squadaegis.pluginrpc.v1.JSONResponse
	24, // 64: squadaegis.pluginrpc.v1.HostAPI.AdminAddTemporaryAdmin:output_type -> squadaegis.pluginrpc.v1.Empty
	24, // 65: squadaegis.pluginrpc.v1.HostAPI.AdminRemoveTemporaryAdmin:output_type -> squadaegis.pluginrpc.v1.Empty
	24, // 66: squadaegis.pluginrpc.v1.HostAPI.AdminRemoveTemporaryAdminRole:output_type -> squadaegis.pluginrpc.v1.Empty
	0,  // 67: squadaegis.pluginrpc.v1.HostAPI.AdminGetPlayerAdminStatus:output_type -> squadaegis.pluginrpc.v1.JSONResponse
	0,  // 68: squadaegis.pluginrpc.v1.HostAPI.AdminListTemporaryAdmins:output_type -> squadaegis.pluginrpc.v1.JSONResponse
	24, // 69: squadaegis.pluginrpc.v1.HostAPI.EventPublishEvent:output_type -> squadaegis.pluginrpc.v1.Empty
	20, // 70: squadaegis.pluginrpc.v1.HostAPI.DiscordSendMessage:output_type -> squadaegis.pluginrpc.v1.DiscordMessageResponse
	20, // 71: squadaegis.pluginrpc.v1.HostAPI.DiscordSendEmbed:output_type -> squadaegis.pluginrpc.v1.DiscordMessageResponse
	22, // 72: squadaegis.pluginrpc.v1.HostAPI.ConnectorCall:output_type -> squadaegis.pluginrpc.v1.ConnectorCallResponse
	37, // [37:73] is the sub-list for method output_type
	1,  // [1:37] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_pkg_pluginrpc_proto_hostapi_proto_init() }
func file_pkg_pluginrpc_proto_hostapi_proto_init() {
	if File_pkg_pluginrpc_proto_hostapi_proto != nil {
		return
	}
	file_pkg_pluginrpc_proto_plugin_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_pluginrpc_proto_hostapi_proto_rawDesc), len(file_pkg_pluginrpc_proto_hostapi_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_pluginrpc_proto_hostapi_proto_goTypes,
		DependencyIndexes: file_pkg_pluginrpc_proto_hostapi_proto_depIdxs,
		MessageInfos:      file_pkg_pluginrpc_proto_hostapi_proto_msgTypes,
	}.Build()
	File_pkg_pluginrpc_proto_hostapi_proto = out.File
	file_pkg_pluginrpc_proto_hostapi_proto_goTypes = nil
	file_pkg_pluginrpc_proto_hostapi_proto_depIdxs = nil
}
