// HostAPI is the plugin-to-host service. The plugin subprocess dials the
// host on the broker ID supplied via Plugin.Initialize and then invokes
// methods on this service. All host-side authorization (rate limiting,
// payload caps, connector scope, Discord channel allowlist, etc.) lives in
// the host's implementation of this service.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v7.34.1
// source: pkg/pluginrpc/proto/hostapi.proto

package pluginrpcpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HostAPI_LogInfo_FullMethodName                               = "/squadaegis.pluginrpc.v1.HostAPI/LogInfo"
	HostAPI_LogWarn_FullMethodName                               = "/squadaegis.pluginrpc.v1.HostAPI/LogWarn"
	HostAPI_LogError_FullMethodName                              = "/squadaegis.pluginrpc.v1.HostAPI/LogError"
	HostAPI_LogDebug_FullMethodName                              = "/squadaegis.pluginrpc.v1.HostAPI/LogDebug"
	HostAPI_RconSendCommand_FullMethodName                       = "/squadaegis.pluginrpc.v1.HostAPI/RconSendCommand"
	HostAPI_RconBroadcast_FullMethodName                         = "/squadaegis.pluginrpc.v1.HostAPI/RconBroadcast"
	HostAPI_RconSendWarningToPlayer_FullMethodName               = "/squadaegis.pluginrpc.v1.HostAPI/RconSendWarningToPlayer"
	HostAPI_RconKickPlayer_FullMethodName                        = "/squadaegis.pluginrpc.v1.HostAPI/RconKickPlayer"
	HostAPI_RconBanPlayer_FullMethodName                         = "/squadaegis.pluginrpc.v1.HostAPI/RconBanPlayer"
	HostAPI_RconBanWithEvidence_FullMethodName                   = "/squadaegis.pluginrpc.v1.HostAPI/RconBanWithEvidence"
	HostAPI_RconWarnPlayerWithRule_FullMethodName                = "/squadaegis.pluginrpc.v1.HostAPI/RconWarnPlayerWithRule"
	HostAPI_RconKickPlayerWithRule_FullMethodName                = "/squadaegis.pluginrpc.v1.HostAPI/RconKickPlayerWithRule"
	HostAPI_RconBanPlayerWithRule_FullMethodName                 = "/squadaegis.pluginrpc.v1.HostAPI/RconBanPlayerWithRule"
	HostAPI_RconBanWithEvidenceAndRule_FullMethodName            = "/squadaegis.pluginrpc.v1.HostAPI/RconBanWithEvidenceAndRule"
	HostAPI_RconBanWithEvidenceAndRuleAndMetadata_FullMethodName = "/squadaegis.pluginrpc.v1.HostAPI/RconBanWithEvidenceAndRuleAndMetadata"
	HostAPI_RconRemovePlayerFromSquad_FullMethodName             = "/squadaegis.pluginrpc.v1.HostAPI/RconRemovePlayerFromSquad"
	HostAPI_RconRemovePlayerFromSquadById_FullMethodName         = "/squadaegis.pluginrpc.v1.HostAPI/RconRemovePlayerFromSquadById"
	HostAPI_ServerGetServerID_FullMethodName                     = "/squadaegis.pluginrpc.v1.HostAPI/ServerGetServerID"
	HostAPI_ServerGetServerInfo_FullMethodName                   = "/squadaegis.pluginrpc.v1.HostAPI/ServerGetServerInfo"
	HostAPI_ServerGetPlayers_FullMethodName                      = "/squadaegis.pluginrpc.v1.HostAPI/ServerGetPlayers"
	HostAPI_ServerGetAdmins_FullMethodName                       = "/squadaegis.pluginrpc.v1.HostAPI/ServerGetAdmins"
	HostAPI_ServerGetSquads_FullMethodName                       = "/squadaegis.pluginrpc.v1.HostAPI/ServerGetSquads"
	HostAPI_DatabaseGetPluginData_FullMethodName                 = "/squadaegis.pluginrpc.v1.HostAPI/DatabaseGetPluginData"
	HostAPI_DatabaseSetPluginData_FullMethodName                 = "/squadaegis.pluginrpc.v1.HostAPI/DatabaseSetPluginData"
	HostAPI_DatabaseDeletePluginData_FullMethodName              = "/squadaegis.pluginrpc.v1.HostAPI/DatabaseDeletePluginData"
	HostAPI_RuleListServerRules_FullMethodName                   = "/squadaegis.pluginrpc.v1.HostAPI/RuleListServerRules"
	HostAPI_RuleListServerRuleActions_FullMethodName             = "/squadaegis.pluginrpc.v1.HostAPI/RuleListServerRuleActions"
	HostAPI_AdminAddTemporaryAdmin_FullMethodName                = "/squadaegis.pluginrpc.v1.HostAPI/AdminAddTemporaryAdmin"
	HostAPI_AdminRemoveTemporaryAdmin_FullMethodName             = "/squadaegis.pluginrpc.v1.HostAPI/AdminRemoveTemporaryAdmin"
	HostAPI_AdminRemoveTemporaryAdminRole_FullMethodName         = "/squadaegis.pluginrpc.v1.HostAPI/AdminRemoveTemporaryAdminRole"
	HostAPI_AdminGetPlayerAdminStatus_FullMethodName             = "/squadaegis.pluginrpc.v1.HostAPI/AdminGetPlayerAdminStatus"
	HostAPI_AdminListTemporaryAdmins_FullMethodName              = "/squadaegis.pluginrpc.v1.HostAPI/AdminListTemporaryAdmins"
	HostAPI_EventPublishEvent_FullMethodName                     = "/squadaegis.pluginrpc.v1.HostAPI/EventPublishEvent"
	HostAPI_DiscordSendMessage_FullMethodName                    = "/squadaegis.pluginrpc.v1.HostAPI/DiscordSendMessage"
	HostAPI_DiscordSendEmbed_FullMethodName                      = "/squadaegis.pluginrpc.v1.HostAPI/DiscordSendEmbed"
	HostAPI_ConnectorCall_FullMethodName                         = "/squadaegis.pluginrpc.v1.HostAPI/ConnectorCall"
)

// HostAPIClient is the client API for HostAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HostAPIClient interface {
	// -- Log -------------------------------------------------------------
	LogInfo(ctx context.Context, in *LogRequest, opts ...grpc.CallOption) (*Empty, error)
	LogWarn(ctx context.Context, in *LogRequest, opts ...grpc.CallOption) (*Empty, error)
	LogError(ctx context.Context, in *LogRequest, opts ...grpc.CallOption) (*Empty, error)
	LogDebug(ctx context.Context, in *LogRequest, opts ...grpc.CallOption) (*Empty, error)
	// -- Rcon ------------------------------------------------------------
	RconSendCommand(ctx context.Context, in *RconCommandRequest, opts ...grpc.CallOption) (*RconCommandResponse, error)
	RconBroadcast(ctx context.Context, in *RconBroadcastRequest, opts ...grpc.CallOption) (*Empty, error)
	RconSendWarningToPlayer(ctx context.Context, in *RconWarnPlayerRequest, opts ...grpc.CallOption) (*Empty, error)
	RconKickPlayer(ctx context.Context, in *RconKickRequest, opts ...grpc.CallOption) (*Empty, error)
	RconBanPlayer(ctx context.Context, in *RconBanRequest, opts ...grpc.CallOption) (*Empty, error)
	RconBanWithEvidence(ctx context.Context, in *RconBanRequest, opts ...grpc.CallOption) (*BanResultResponse, error)
	RconWarnPlayerWithRule(ctx context.Context, in *RconBanRequest, opts ...grpc.CallOption) (*Empty, error)
	RconKickPlayerWithRule(ctx context.Context, in *RconBanRequest, opts ...grpc.CallOption) (*Empty, error)
	RconBanPlayerWithRule(ctx context.Context, in *RconBanRequest, opts ...grpc.CallOption) (*Empty, error)
	RconBanWithEvidenceAndRule(ctx context.Context, in *RconBanRequest, opts ...grpc.CallOption) (*BanResultResponse, error)
	RconBanWithEvidenceAndRuleAndMetadata(ctx context.Context, in *RconBanRequest, opts ...grpc.CallOption) (*BanResultResponse, error)
	RconRemovePlayerFromSquad(ctx context.Context, in *RconRemoveSquadRequest, opts ...grpc.CallOption) (*Empty, error)
	RconRemovePlayerFromSquadById(ctx context.Context, in *RconRemoveSquadRequest, opts ...grpc.CallOption) (*Empty, error)
	// -- Server ----------------------------------------------------------
	ServerGetServerID(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*StringResponse, error)
	ServerGetServerInfo(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*JSONResponse, error)
	ServerGetPlayers(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*JSONResponse, error)
	ServerGetAdmins(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*JSONResponse, error)
	ServerGetSquads(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*JSONResponse, error)
	// -- Database --------------------------------------------------------
	DatabaseGetPluginData(ctx context.Context, in *DatabaseRequest, opts ...grpc.CallOption) (*DatabaseResponse, error)
	DatabaseSetPluginData(ctx context.Context, in *DatabaseRequest, opts ...grpc.CallOption) (*Empty, error)
	DatabaseDeletePluginData(ctx context.Context, in *DatabaseRequest, opts ...grpc.CallOption) (*Empty, error)
	// -- Rule ------------------------------------------------------------
	RuleListServerRules(ctx context.Context, in *ListRulesRequest, opts ...grpc.CallOption) (*JSONResponse, error)
	RuleListServerRuleActions(ctx context.Context, in *ListRuleActionsRequest, opts ...grpc.CallOption) (*JSONResponse, error)
	// -- Admin -----------------------------------------------------------
	AdminAddTemporaryAdmin(ctx context.Context, in *AddTempAdminRequest, opts ...grpc.CallOption) (*Empty, error)
	AdminRemoveTemporaryAdmin(ctx context.Context, in *RemoveTempAdminRequest, opts ...grpc.CallOption) (*Empty, error)
	AdminRemoveTemporaryAdminRole(ctx context.Context, in *RemoveTempAdminRequest, opts ...grpc.CallOption) (*Empty, error)
	AdminGetPlayerAdminStatus(ctx context.Context, in *PlayerIDRequest, opts ...grpc.CallOption) (*JSONResponse, error)
	AdminListTemporaryAdmins(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*JSONResponse, error)
	// -- Event -----------------------------------------------------------
	EventPublishEvent(ctx context.Context, in *PublishEventRequest, opts ...grpc.CallOption) (*Empty, error)
	// -- Discord ---------------------------------------------------------
	DiscordSendMessage(ctx context.Context, in *DiscordMessageRequest, opts ...grpc.CallOption) (*DiscordMessageResponse, error)
	DiscordSendEmbed(ctx context.Context, in *DiscordMessageRequest, opts ...grpc.CallOption) (*DiscordMessageResponse, error)
	// -- Connector -------------------------------------------------------
	ConnectorCall(ctx context.Context, in *ConnectorCallRequest, opts ...grpc.CallOption) (*ConnectorCallResponse, error)
}

type hostAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewHostAPIClient(cc grpc.ClientConnInterface) HostAPIClient {
	return &hostAPIClient{cc}
}

func (c *hostAPIClient) LogInfo(ctx context.Context, in *LogRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, HostAPI_LogInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostAPIClient) LogWarn(ctx context.Context, in *LogRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, HostAPI_LogWarn_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostAPIClient) LogError(ctx context.Context, in *LogRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, HostAPI_LogError_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostAPIClient) LogDebug(ctx context.Context, in *LogRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, HostAPI_LogDebug_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostAPIClient) RconSendCommand(ctx context.Context, in *RconCommandRequest, opts ...grpc.CallOption) (*RconCommandResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RconCommandResponse)
	err := c.cc.Invoke(ctx, HostAPI_RconSendCommand_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostAPIClient) RconBroadcast(ctx context.Context, in *RconBroadcastRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, HostAPI_RconBroadcast_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostAPIClient) RconSendWarningToPlayer(ctx context.Context, in *RconWarnPlayerRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, HostAPI_RconSendWarningToPlayer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostAPIClient) RconKickPlayer(ctx context.Context, in *RconKickRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, HostAPI_RconKickPlayer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostAPIClient) RconBanPlayer(ctx context.Context, in *RconBanRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, HostAPI_RconBanPlayer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostAPIClient) RconBanWithEvidence(ctx context.Context, in *RconBanRequest, opts ...grpc.CallOption) (*BanResultResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BanResultResponse)
	err := c.cc.Invoke(ctx, HostAPI_RconBanWithEvidence_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostAPIClient) RconWarnPlayerWithRule(ctx context.Context, in *RconBanRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, HostAPI_RconWarnPlayerWithRule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostAPIClient) RconKickPlayerWithRule(ctx context.Context, in *RconBanRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, HostAPI_RconKickPlayerWithRule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostAPIClient) RconBanPlayerWithRule(ctx context.Context, in *RconBanRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, HostAPI_RconBanPlayerWithRule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostAPIClient) RconBanWithEvidenceAndRule(ctx context.Context, in *RconBanRequest, opts ...grpc.CallOption) (*BanResultResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BanResultResponse)
	err := c.cc.Invoke(ctx, HostAPI_RconBanWithEvidenceAndRule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostAPIClient) RconBanWithEvidenceAndRuleAndMetadata(ctx context.Context, in *RconBanRequest, opts ...grpc.CallOption) (*BanResultResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BanResultResponse)
	err := c.cc.Invoke(ctx, HostAPI_RconBanWithEvidenceAndRuleAndMetadata_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostAPIClient) RconRemovePlayerFromSquad(ctx context.Context, in *RconRemoveSquadRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, HostAPI_RconRemovePlayerFromSquad_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostAPIClient) RconRemovePlayerFromSquadById(ctx context.Context, in *RconRemoveSquadRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, HostAPI_RconRemovePlayerFromSquadById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostAPIClient) ServerGetServerID(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*StringResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StringResponse)
	err := c.cc.Invoke(ctx, HostAPI_ServerGetServerID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostAPIClient) ServerGetServerInfo(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*JSONResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JSONResponse)
	err := c.cc.Invoke(ctx, HostAPI_ServerGetServerInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostAPIClient) ServerGetPlayers(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*JSONResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JSONResponse)
	err := c.cc.Invoke(ctx, HostAPI_ServerGetPlayers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostAPIClient) ServerGetAdmins(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*JSONResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JSONResponse)
	err := c.cc.Invoke(ctx, HostAPI_ServerGetAdmins_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostAPIClient) ServerGetSquads(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*JSONResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JSONResponse)
	err := c.cc.Invoke(ctx, HostAPI_ServerGetSquads_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostAPIClient) DatabaseGetPluginData(ctx context.Context, in *DatabaseRequest, opts ...grpc.CallOption) (*DatabaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DatabaseResponse)
	err := c.cc.Invoke(ctx, HostAPI_DatabaseGetPluginData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostAPIClient) DatabaseSetPluginData(ctx context.Context, in *DatabaseRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, HostAPI_DatabaseSetPluginData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostAPIClient) DatabaseDeletePluginData(ctx context.Context, in *DatabaseRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, HostAPI_DatabaseDeletePluginData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostAPIClient) RuleListServerRules(ctx context.Context, in *ListRulesRequest, opts ...grpc.CallOption) (*JSONResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JSONResponse)
	err := c.cc.Invoke(ctx, HostAPI_RuleListServerRules_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostAPIClient) RuleListServerRuleActions(ctx context.Context, in *ListRuleActionsRequest, opts ...grpc.CallOption) (*JSONResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JSONResponse)
	err := c.cc.Invoke(ctx, HostAPI_RuleListServerRuleActions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostAPIClient) AdminAddTemporaryAdmin(ctx context.Context, in *AddTempAdminRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, HostAPI_AdminAddTemporaryAdmin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostAPIClient) AdminRemoveTemporaryAdmin(ctx context.Context, in *RemoveTempAdminRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, HostAPI_AdminRemoveTemporaryAdmin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostAPIClient) AdminRemoveTemporaryAdminRole(ctx context.Context, in *RemoveTempAdminRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, HostAPI_AdminRemoveTemporaryAdminRole_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostAPIClient) AdminGetPlayerAdminStatus(ctx context.Context, in *PlayerIDRequest, opts ...grpc.CallOption) (*JSONResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JSONResponse)
	err := c.cc.Invoke(ctx, HostAPI_AdminGetPlayerAdminStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostAPIClient) AdminListTemporaryAdmins(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*JSONResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JSONResponse)
	err := c.cc.Invoke(ctx, HostAPI_AdminListTemporaryAdmins_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostAPIClient) EventPublishEvent(ctx context.Context, in *PublishEventRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, HostAPI_EventPublishEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostAPIClient) DiscordSendMessage(ctx context.Context, in *DiscordMessageRequest, opts ...grpc.CallOption) (*DiscordMessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DiscordMessageResponse)
	err := c.cc.Invoke(ctx, HostAPI_DiscordSendMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostAPIClient) DiscordSendEmbed(ctx context.Context, in *DiscordMessageRequest, opts ...grpc.CallOption) (*DiscordMessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DiscordMessageResponse)
	err := c.cc.Invoke(ctx, HostAPI_DiscordSendEmbed_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostAPIClient) ConnectorCall(ctx context.Context, in *ConnectorCallRequest, opts ...grpc.CallOption) (*ConnectorCallResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConnectorCallResponse)
	err := c.cc.Invoke(ctx, HostAPI_ConnectorCall_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HostAPIServer is the server API for HostAPI service.
// All implementations must embed UnimplementedHostAPIServer
// for forward compatibility.
type HostAPIServer interface {
	// -- Log -------------------------------------------------------------
	LogInfo(context.Context, *LogRequest) (*Empty, error)
	LogWarn(context.Context, *LogRequest) (*Empty, error)
	LogError(context.Context, *LogRequest) (*Empty, error)
	LogDebug(context.Context, *LogRequest) (*Empty, error)
	// -- Rcon ------------------------------------------------------------
	RconSendCommand(context.Context, *RconCommandRequest) (*RconCommandResponse, error)
	RconBroadcast(context.Context, *RconBroadcastRequest) (*Empty, error)
	RconSendWarningToPlayer(context.Context, *RconWarnPlayerRequest) (*Empty, error)
	RconKickPlayer(context.Context, *RconKickRequest) (*Empty, error)
	RconBanPlayer(context.Context, *RconBanRequest) (*Empty, error)
	RconBanWithEvidence(context.Context, *RconBanRequest) (*BanResultResponse, error)
	RconWarnPlayerWithRule(context.Context, *RconBanRequest) (*Empty, error)
	RconKickPlayerWithRule(context.Context, *RconBanRequest) (*Empty, error)
	RconBanPlayerWithRule(context.Context, *RconBanRequest) (*Empty, error)
	RconBanWithEvidenceAndRule(context.Context, *RconBanRequest) (*BanResultResponse, error)
	RconBanWithEvidenceAndRuleAndMetadata(context.Context, *RconBanRequest) (*BanResultResponse, error)
	RconRemovePlayerFromSquad(context.Context, *RconRemoveSquadRequest) (*Empty, error)
	RconRemovePlayerFromSquadById(context.Context, *RconRemoveSquadRequest) (*Empty, error)
	// -- Server ----------------------------------------------------------
	ServerGetServerID(context.Context, *Empty) (*StringResponse, error)
	ServerGetServerInfo(context.Context, *Empty) (*JSONResponse, error)
	ServerGetPlayers(context.Context, *Empty) (*JSONResponse, error)
	ServerGetAdmins(context.Context, *Empty) (*JSONResponse, error)
	ServerGetSquads(context.Context, *Empty) (*JSONResponse, error)
	// -- Database --------------------------------------------------------
	DatabaseGetPluginData(context.Context, *DatabaseRequest) (*DatabaseResponse, error)
	DatabaseSetPluginData(context.Context, *DatabaseRequest) (*Empty, error)
	DatabaseDeletePluginData(context.Context, *DatabaseRequest) (*Empty, error)
	// -- Rule ------------------------------------------------------------
	RuleListServerRules(context.Context, *ListRulesRequest) (*JSONResponse, error)
	RuleListServerRuleActions(context.Context, *ListRuleActionsRequest) (*JSONResponse, error)
	// -- Admin -----------------------------------------------------------
	AdminAddTemporaryAdmin(context.Context, *AddTempAdminRequest) (*Empty, error)
	AdminRemoveTemporaryAdmin(context.Context, *RemoveTempAdminRequest) (*Empty, error)
	AdminRemoveTemporaryAdminRole(context.Context, *RemoveTempAdminRequest) (*Empty, error)
	AdminGetPlayerAdminStatus(context.Context, *PlayerIDRequest) (*JSONResponse, error)
	AdminListTemporaryAdmins(context.Context, *Empty) (*JSONResponse, error)
	// -- Event -----------------------------------------------------------
	EventPublishEvent(context.Context, *PublishEventRequest) (*Empty, error)
	// -- Discord ---------------------------------------------------------
	DiscordSendMessage(context.Context, *DiscordMessageRequest) (*DiscordMessageResponse, error)
	DiscordSendEmbed(context.Context, *DiscordMessageRequest) (*DiscordMessageResponse, error)
	// -- Connector -------------------------------------------------------
	ConnectorCall(context.Context, *ConnectorCallRequest) (*ConnectorCallResponse, error)
	mustEmbedUnimplementedHostAPIServer()
}

// UnimplementedHostAPIServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHostAPIServer struct{}

func (UnimplementedHostAPIServer) LogInfo(context.Context, *LogRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method LogInfo not implemented")
}
func (UnimplementedHostAPIServer) LogWarn(context.Context, *LogRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method LogWarn not implemented")
}
func (UnimplementedHostAPIServer) LogError(context.Context, *LogRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method LogError not implemented")
}
func (UnimplementedHostAPIServer) LogDebug(context.Context, *LogRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method LogDebug not implemented")
}
func (UnimplementedHostAPIServer) RconSendCommand(context.Context, *RconCommandRequest) (*RconCommandResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RconSendCommand not implemented")
}
func (UnimplementedHostAPIServer) RconBroadcast(context.Context, *RconBroadcastRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method RconBroadcast not implemented")
}
func (UnimplementedHostAPIServer) RconSendWarningToPlayer(context.Context, *RconWarnPlayerRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method RconSendWarningToPlayer not implemented")
}
func (UnimplementedHostAPIServer) RconKickPlayer(context.Context, *RconKickRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method RconKickPlayer not implemented")
}
func (UnimplementedHostAPIServer) RconBanPlayer(context.Context, *RconBanRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method RconBanPlayer not implemented")
}
func (UnimplementedHostAPIServer) RconBanWithEvidence(context.Context, *RconBanRequest) (*BanResultResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RconBanWithEvidence not implemented")
}
func (UnimplementedHostAPIServer) RconWarnPlayerWithRule(context.Context, *RconBanRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method RconWarnPlayerWithRule not implemented")
}
func (UnimplementedHostAPIServer) RconKickPlayerWithRule(context.Context, *RconBanRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method RconKickPlayerWithRule not implemented")
}
func (UnimplementedHostAPIServer) RconBanPlayerWithRule(context.Context, *RconBanRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method RconBanPlayerWithRule not implemented")
}
func (UnimplementedHostAPIServer) RconBanWithEvidenceAndRule(context.Context, *RconBanRequest) (*BanResultResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RconBanWithEvidenceAndRule not implemented")
}
func (UnimplementedHostAPIServer) RconBanWithEvidenceAndRuleAndMetadata(context.Context, *RconBanRequest) (*BanResultResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RconBanWithEvidenceAndRuleAndMetadata not implemented")
}
func (UnimplementedHostAPIServer) RconRemovePlayerFromSquad(context.Context, *RconRemoveSquadRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method RconRemovePlayerFromSquad not implemented")
}
func (UnimplementedHostAPIServer) RconRemovePlayerFromSquadById(context.Context, *RconRemoveSquadRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method RconRemovePlayerFromSquadById not implemented")
}
func (UnimplementedHostAPIServer) ServerGetServerID(context.Context, *Empty) (*StringResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ServerGetServerID not implemented")
}
func (UnimplementedHostAPIServer) ServerGetServerInfo(context.Context, *Empty) (*JSONResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ServerGetServerInfo not implemented")
}
func (UnimplementedHostAPIServer) ServerGetPlayers(context.Context, *Empty) (*JSONResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ServerGetPlayers not implemented")
}
func (UnimplementedHostAPIServer) ServerGetAdmins(context.Context, *Empty) (*JSONResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ServerGetAdmins not implemented")
}
func (UnimplementedHostAPIServer) ServerGetSquads(context.Context, *Empty) (*JSONResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ServerGetSquads not implemented")
}
func (UnimplementedHostAPIServer) DatabaseGetPluginData(context.Context, *DatabaseRequest) (*DatabaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DatabaseGetPluginData not implemented")
}
func (UnimplementedHostAPIServer) DatabaseSetPluginData(context.Context, *DatabaseRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DatabaseSetPluginData not implemented")
}
func (UnimplementedHostAPIServer) DatabaseDeletePluginData(context.Context, *DatabaseRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DatabaseDeletePluginData not implemented")
}
func (UnimplementedHostAPIServer) RuleListServerRules(context.Context, *ListRulesRequest) (*JSONResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RuleListServerRules not implemented")
}
func (UnimplementedHostAPIServer) RuleListServerRuleActions(context.Context, *ListRuleActionsRequest) (*JSONResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RuleListServerRuleActions not implemented")
}
func (UnimplementedHostAPIServer) AdminAddTemporaryAdmin(context.Context, *AddTempAdminRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method AdminAddTemporaryAdmin not implemented")
}
func (UnimplementedHostAPIServer) AdminRemoveTemporaryAdmin(context.Context, *RemoveTempAdminRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method AdminRemoveTemporaryAdmin not implemented")
}
func (UnimplementedHostAPIServer) AdminRemoveTemporaryAdminRole(context.Context, *RemoveTempAdminRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method AdminRemoveTemporaryAdminRole not implemented")
}
func (UnimplementedHostAPIServer) AdminGetPlayerAdminStatus(context.Context, *PlayerIDRequest) (*JSONResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AdminGetPlayerAdminStatus not implemented")
}
func (UnimplementedHostAPIServer) AdminListTemporaryAdmins(context.Context, *Empty) (*JSONResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AdminListTemporaryAdmins not implemented")
}
func (UnimplementedHostAPIServer) EventPublishEvent(context.Context, *PublishEventRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method EventPublishEvent not implemented")
}
func (UnimplementedHostAPIServer) DiscordSendMessage(context.Context, *DiscordMessageRequest) (*DiscordMessageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DiscordSendMessage not implemented")
}
func (UnimplementedHostAPIServer) DiscordSendEmbed(context.Context, *DiscordMessageRequest) (*DiscordMessageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DiscordSendEmbed not implemented")
}
func (UnimplementedHostAPIServer) ConnectorCall(context.Context, *ConnectorCallRequest) (*ConnectorCallResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ConnectorCall not implemented")
}
func (UnimplementedHostAPIServer) mustEmbedUnimplementedHostAPIServer() {}
func (UnimplementedHostAPIServer) testEmbeddedByValue()                 {}

// UnsafeHostAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HostAPIServer will
// result in compilation errors.
type UnsafeHostAPIServer interface {
	mustEmbedUnimplementedHostAPIServer()
}

func RegisterHostAPIServer(s grpc.ServiceRegistrar, srv HostAPIServer) {
	// If the following call panics, it indicates UnimplementedHostAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HostAPI_ServiceDesc, srv)
}

func _HostAPI_LogInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostAPIServer).LogInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostAPI_LogInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostAPIServer).LogInfo(ctx, req.(*LogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostAPI_LogWarn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostAPIServer).LogWarn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostAPI_LogWarn_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostAPIServer).LogWarn(ctx, req.(*LogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostAPI_LogError_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostAPIServer).LogError(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostAPI_LogError_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostAPIServer).LogError(ctx, req.(*LogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostAPI_LogDebug_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostAPIServer).LogDebug(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostAPI_LogDebug_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostAPIServer).LogDebug(ctx, req.(*LogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostAPI_RconSendCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RconCommandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostAPIServer).RconSendCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostAPI_RconSendCommand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostAPIServer).RconSendCommand(ctx, req.(*RconCommandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostAPI_RconBroadcast_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RconBroadcastRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostAPIServer).RconBroadcast(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostAPI_RconBroadcast_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostAPIServer).RconBroadcast(ctx, req.(*RconBroadcastRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostAPI_RconSendWarningToPlayer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RconWarnPlayerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostAPIServer).RconSendWarningToPlayer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostAPI_RconSendWarningToPlayer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostAPIServer).RconSendWarningToPlayer(ctx, req.(*RconWarnPlayerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostAPI_RconKickPlayer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RconKickRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostAPIServer).RconKickPlayer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostAPI_RconKickPlayer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostAPIServer).RconKickPlayer(ctx, req.(*RconKickRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostAPI_RconBanPlayer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RconBanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostAPIServer).RconBanPlayer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostAPI_RconBanPlayer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostAPIServer).RconBanPlayer(ctx, req.(*RconBanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostAPI_RconBanWithEvidence_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RconBanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostAPIServer).RconBanWithEvidence(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostAPI_RconBanWithEvidence_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostAPIServer).RconBanWithEvidence(ctx, req.(*RconBanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostAPI_RconWarnPlayerWithRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RconBanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostAPIServer).RconWarnPlayerWithRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostAPI_RconWarnPlayerWithRule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostAPIServer).RconWarnPlayerWithRule(ctx, req.(*RconBanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostAPI_RconKickPlayerWithRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RconBanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostAPIServer).RconKickPlayerWithRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostAPI_RconKickPlayerWithRule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostAPIServer).RconKickPlayerWithRule(ctx, req.(*RconBanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostAPI_RconBanPlayerWithRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RconBanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostAPIServer).RconBanPlayerWithRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostAPI_RconBanPlayerWithRule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostAPIServer).RconBanPlayerWithRule(ctx, req.(*RconBanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostAPI_RconBanWithEvidenceAndRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RconBanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostAPIServer).RconBanWithEvidenceAndRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostAPI_RconBanWithEvidenceAndRule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostAPIServer).RconBanWithEvidenceAndRule(ctx, req.(*RconBanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostAPI_RconBanWithEvidenceAndRuleAndMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RconBanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostAPIServer).RconBanWithEvidenceAndRuleAndMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostAPI_RconBanWithEvidenceAndRuleAndMetadata_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostAPIServer).RconBanWithEvidenceAndRuleAndMetadata(ctx, req.(*RconBanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostAPI_RconRemovePlayerFromSquad_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RconRemoveSquadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostAPIServer).RconRemovePlayerFromSquad(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostAPI_RconRemovePlayerFromSquad_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostAPIServer).RconRemovePlayerFromSquad(ctx, req.(*RconRemoveSquadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostAPI_RconRemovePlayerFromSquadById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RconRemoveSquadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostAPIServer).RconRemovePlayerFromSquadById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostAPI_RconRemovePlayerFromSquadById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostAPIServer).RconRemovePlayerFromSquadById(ctx, req.(*RconRemoveSquadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostAPI_ServerGetServerID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostAPIServer).ServerGetServerID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostAPI_ServerGetServerID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostAPIServer).ServerGetServerID(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostAPI_ServerGetServerInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostAPIServer).ServerGetServerInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostAPI_ServerGetServerInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostAPIServer).ServerGetServerInfo(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostAPI_ServerGetPlayers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostAPIServer).ServerGetPlayers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostAPI_ServerGetPlayers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostAPIServer).ServerGetPlayers(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostAPI_ServerGetAdmins_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostAPIServer).ServerGetAdmins(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostAPI_ServerGetAdmins_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostAPIServer).ServerGetAdmins(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostAPI_ServerGetSquads_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostAPIServer).ServerGetSquads(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostAPI_ServerGetSquads_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostAPIServer).ServerGetSquads(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostAPI_DatabaseGetPluginData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DatabaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostAPIServer).DatabaseGetPluginData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostAPI_DatabaseGetPluginData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostAPIServer).DatabaseGetPluginData(ctx, req.(*DatabaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostAPI_DatabaseSetPluginData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DatabaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostAPIServer).DatabaseSetPluginData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostAPI_DatabaseSetPluginData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostAPIServer).DatabaseSetPluginData(ctx, req.(*DatabaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostAPI_DatabaseDeletePluginData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DatabaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostAPIServer).DatabaseDeletePluginData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostAPI_DatabaseDeletePluginData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostAPIServer).DatabaseDeletePluginData(ctx, req.(*DatabaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostAPI_RuleListServerRules_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRulesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostAPIServer).RuleListServerRules(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostAPI_RuleListServerRules_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostAPIServer).RuleListServerRules(ctx, req.(*ListRulesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostAPI_RuleListServerRuleActions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRuleActionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostAPIServer).RuleListServerRuleActions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostAPI_RuleListServerRuleActions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostAPIServer).RuleListServerRuleActions(ctx, req.(*ListRuleActionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostAPI_AdminAddTemporaryAdmin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddTempAdminRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostAPIServer).AdminAddTemporaryAdmin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostAPI_AdminAddTemporaryAdmin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostAPIServer).AdminAddTemporaryAdmin(ctx, req.(*AddTempAdminRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostAPI_AdminRemoveTemporaryAdmin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveTempAdminRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostAPIServer).AdminRemoveTemporaryAdmin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostAPI_AdminRemoveTemporaryAdmin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostAPIServer).AdminRemoveTemporaryAdmin(ctx, req.(*RemoveTempAdminRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostAPI_AdminRemoveTemporaryAdminRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveTempAdminRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostAPIServer).AdminRemoveTemporaryAdminRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostAPI_AdminRemoveTemporaryAdminRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostAPIServer).AdminRemoveTemporaryAdminRole(ctx, req.(*RemoveTempAdminRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostAPI_AdminGetPlayerAdminStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlayerIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostAPIServer).AdminGetPlayerAdminStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostAPI_AdminGetPlayerAdminStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostAPIServer).AdminGetPlayerAdminStatus(ctx, req.(*PlayerIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostAPI_AdminListTemporaryAdmins_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostAPIServer).AdminListTemporaryAdmins(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostAPI_AdminListTemporaryAdmins_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostAPIServer).AdminListTemporaryAdmins(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostAPI_EventPublishEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostAPIServer).EventPublishEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostAPI_EventPublishEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostAPIServer).EventPublishEvent(ctx, req.(*PublishEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostAPI_DiscordSendMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DiscordMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostAPIServer).DiscordSendMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostAPI_DiscordSendMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostAPIServer).DiscordSendMessage(ctx, req.(*DiscordMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostAPI_DiscordSendEmbed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DiscordMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostAPIServer).DiscordSendEmbed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostAPI_DiscordSendEmbed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostAPIServer).DiscordSendEmbed(ctx, req.(*DiscordMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostAPI_ConnectorCall_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConnectorCallRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostAPIServer).ConnectorCall(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostAPI_ConnectorCall_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostAPIServer).ConnectorCall(ctx, req.(*ConnectorCallRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HostAPI_ServiceDesc is the grpc.ServiceDesc for HostAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HostAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "squadaegis.pluginrpc.v1.HostAPI",
	HandlerType: (*HostAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LogInfo",
			Handler:    _HostAPI_LogInfo_Handler,
		},
		{
			MethodName: "LogWarn",
			Handler:    _HostAPI_LogWarn_Handler,
		},
		{
			MethodName: "LogError",
			Handler:    _HostAPI_LogError_Handler,
		},
		{
			MethodName: "LogDebug",
			Handler:    _HostAPI_LogDebug_Handler,
		},
		{
			MethodName: "RconSendCommand",
			Handler:    _HostAPI_RconSendCommand_Handler,
		},
		{
			MethodName: "RconBroadcast",
			Handler:    _HostAPI_RconBroadcast_Handler,
		},
		{
			MethodName: "RconSendWarningToPlayer",
			Handler:    _HostAPI_RconSendWarningToPlayer_Handler,
		},
		{
			MethodName: "RconKickPlayer",
			Handler:    _HostAPI_RconKickPlayer_Handler,
		},
		{
			MethodName: "RconBanPlayer",
			Handler:    _HostAPI_RconBanPlayer_Handler,
		},
		{
			MethodName: "RconBanWithEvidence",
			Handler:    _HostAPI_RconBanWithEvidence_Handler,
		},
		{
			MethodName: "RconWarnPlayerWithRule",
			Handler:    _HostAPI_RconWarnPlayerWithRule_Handler,
		},
		{
			MethodName: "RconKickPlayerWithRule",
			Handler:    _HostAPI_RconKickPlayerWithRule_Handler,
		},
		{
			MethodName: "RconBanPlayerWithRule",
			Handler:    _HostAPI_RconBanPlayerWithRule_Handler,
		},
		{
			MethodName: "RconBanWithEvidenceAndRule",
			Handler:    _HostAPI_RconBanWithEvidenceAndRule_Handler,
		},
		{
			MethodName: "RconBanWithEvidenceAndRuleAndMetadata",
			Handler:    _HostAPI_RconBanWithEvidenceAndRuleAndMetadata_Handler,
		},
		{
			MethodName: "RconRemovePlayerFromSquad",
			Handler:    _HostAPI_RconRemovePlayerFromSquad_Handler,
		},
		{
			MethodName: "RconRemovePlayerFromSquadById",
			Handler:    _HostAPI_RconRemovePlayerFromSquadById_Handler,
		},
		{
			MethodName: "ServerGetServerID",
			Handler:    _HostAPI_ServerGetServerID_Handler,
		},
		{
			MethodName: "ServerGetServerInfo",
			Handler:    _HostAPI_ServerGetServerInfo_Handler,
		},
		{
			MethodName: "ServerGetPlayers",
			Handler:    _HostAPI_ServerGetPlayers_Handler,
		},
		{
			MethodName: "ServerGetAdmins",
			Handler:    _HostAPI_ServerGetAdmins_Handler,
		},
		{
			MethodName: "ServerGetSquads",
			Handler:    _HostAPI_ServerGetSquads_Handler,
		},
		{
			MethodName: "DatabaseGetPluginData",
			Handler:    _HostAPI_DatabaseGetPluginData_Handler,
		},
		{
			MethodName: "DatabaseSetPluginData",
			Handler:    _HostAPI_DatabaseSetPluginData_Handler,
		},
		{
			MethodName: "DatabaseDeletePluginData",
			Handler:    _HostAPI_DatabaseDeletePluginData_Handler,
		},
		{
			MethodName: "RuleListServerRules",
			Handler:    _HostAPI_RuleListServerRules_Handler,
		},
		{
			MethodName: "RuleListServerRuleActions",
			Handler:    _HostAPI_RuleListServerRuleActions_Handler,
		},
		{
			MethodName: "AdminAddTemporaryAdmin",
			Handler:    _HostAPI_AdminAddTemporaryAdmin_Handler,
		},
		{
			MethodName: "AdminRemoveTemporaryAdmin",
			Handler:    _HostAPI_AdminRemoveTemporaryAdmin_Handler,
		},
		{
			MethodName: "AdminRemoveTemporaryAdminRole",
			Handler:    _HostAPI_AdminRemoveTemporaryAdminRole_Handler,
		},
		{
			MethodName: "AdminGetPlayerAdminStatus",
			Handler:    _HostAPI_AdminGetPlayerAdminStatus_Handler,
		},
		{
			MethodName: "AdminListTemporaryAdmins",
			Handler:    _HostAPI_AdminListTemporaryAdmins_Handler,
		},
		{
			MethodName: "EventPublishEvent",
			Handler:    _HostAPI_EventPublishEvent_Handler,
		},
		{
			MethodName: "DiscordSendMessage",
			Handler:    _HostAPI_DiscordSendMessage_Handler,
		},
		{
			MethodName: "DiscordSendEmbed",
			Handler:    _HostAPI_DiscordSendEmbed_Handler,
		},
		{
			MethodName: "ConnectorCall",
			Handler:    _HostAPI_ConnectorCall_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/pluginrpc/proto/hostapi.proto",
}
