// Squad Aegis native plugin wire protocol.
//
// The host invokes the Plugin service on the subprocess. Most fields whose
// shape is plugin-defined (config, command params, event data) travel as
// JSON-encoded bytes so the SDK can keep them as map[string]interface{} on
// either end without forcing every plugin to model a fixed proto schema.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v7.34.1
// source: pkg/pluginrpc/proto/plugin.proto

package pluginrpcpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Plugin_GetDefinition_FullMethodName             = "/squadaegis.pluginrpc.v1.Plugin/GetDefinition"
	Plugin_Initialize_FullMethodName                = "/squadaegis.pluginrpc.v1.Plugin/Initialize"
	Plugin_Start_FullMethodName                     = "/squadaegis.pluginrpc.v1.Plugin/Start"
	Plugin_Stop_FullMethodName                      = "/squadaegis.pluginrpc.v1.Plugin/Stop"
	Plugin_HandleEvent_FullMethodName               = "/squadaegis.pluginrpc.v1.Plugin/HandleEvent"
	Plugin_GetStatus_FullMethodName                 = "/squadaegis.pluginrpc.v1.Plugin/GetStatus"
	Plugin_GetConfig_FullMethodName                 = "/squadaegis.pluginrpc.v1.Plugin/GetConfig"
	Plugin_UpdateConfig_FullMethodName              = "/squadaegis.pluginrpc.v1.Plugin/UpdateConfig"
	Plugin_GetCommands_FullMethodName               = "/squadaegis.pluginrpc.v1.Plugin/GetCommands"
	Plugin_ExecuteCommand_FullMethodName            = "/squadaegis.pluginrpc.v1.Plugin/ExecuteCommand"
	Plugin_GetCommandExecutionStatus_FullMethodName = "/squadaegis.pluginrpc.v1.Plugin/GetCommandExecutionStatus"
)

// PluginClient is the client API for Plugin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Plugin is the host-to-plugin service. Each loaded plugin subprocess
// registers exactly one Plugin server.
type PluginClient interface {
	GetDefinition(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*PluginDefinition, error)
	Initialize(ctx context.Context, in *InitializeRequest, opts ...grpc.CallOption) (*Empty, error)
	Start(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	Stop(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	HandleEvent(ctx context.Context, in *PluginEvent, opts ...grpc.CallOption) (*Empty, error)
	GetStatus(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*StatusResponse, error)
	GetConfig(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ConfigJSON, error)
	UpdateConfig(ctx context.Context, in *ConfigJSON, opts ...grpc.CallOption) (*Empty, error)
	GetCommands(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*CommandList, error)
	ExecuteCommand(ctx context.Context, in *ExecuteCommandRequest, opts ...grpc.CallOption) (*CommandResult, error)
	GetCommandExecutionStatus(ctx context.Context, in *ExecutionIDRequest, opts ...grpc.CallOption) (*CommandExecutionStatus, error)
}

type pluginClient struct {
	cc grpc.ClientConnInterface
}

func NewPluginClient(cc grpc.ClientConnInterface) PluginClient {
	return &pluginClient{cc}
}

func (c *pluginClient) GetDefinition(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*PluginDefinition, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PluginDefinition)
	err := c.cc.Invoke(ctx, Plugin_GetDefinition_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginClient) Initialize(ctx context.Context, in *InitializeRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Plugin_Initialize_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginClient) Start(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Plugin_Start_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginClient) Stop(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Plugin_Stop_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginClient) HandleEvent(ctx context.Context, in *PluginEvent, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Plugin_HandleEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginClient) GetStatus(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, Plugin_GetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginClient) GetConfig(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ConfigJSON, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfigJSON)
	err := c.cc.Invoke(ctx, Plugin_GetConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginClient) UpdateConfig(ctx context.Context, in *ConfigJSON, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Plugin_UpdateConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginClient) GetCommands(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*CommandList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommandList)
	err := c.cc.Invoke(ctx, Plugin_GetCommands_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginClient) ExecuteCommand(ctx context.Context, in *ExecuteCommandRequest, opts ...grpc.CallOption) (*CommandResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommandResult)
	err := c.cc.Invoke(ctx, Plugin_ExecuteCommand_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginClient) GetCommandExecutionStatus(ctx context.Context, in *ExecutionIDRequest, opts ...grpc.CallOption) (*CommandExecutionStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommandExecutionStatus)
	err := c.cc.Invoke(ctx, Plugin_GetCommandExecutionStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PluginServer is the server API for Plugin service.
// All implementations must embed UnimplementedPluginServer
// for forward compatibility.
//
// Plugin is the host-to-plugin service. Each loaded plugin subprocess
// registers exactly one Plugin server.
type PluginServer interface {
	GetDefinition(context.Context, *Empty) (*PluginDefinition, error)
	Initialize(context.Context, *InitializeRequest) (*Empty, error)
	Start(context.Context, *Empty) (*Empty, error)
	Stop(context.Context, *Empty) (*Empty, error)
	HandleEvent(context.Context, *PluginEvent) (*Empty, error)
	GetStatus(context.Context, *Empty) (*StatusResponse, error)
	GetConfig(context.Context, *Empty) (*ConfigJSON, error)
	UpdateConfig(context.Context, *ConfigJSON) (*Empty, error)
	GetCommands(context.Context, *Empty) (*CommandList, error)
	ExecuteCommand(context.Context, *ExecuteCommandRequest) (*CommandResult, error)
	GetCommandExecutionStatus(context.Context, *ExecutionIDRequest) (*CommandExecutionStatus, error)
	mustEmbedUnimplementedPluginServer()
}

// UnimplementedPluginServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPluginServer struct{}

func (UnimplementedPluginServer) GetDefinition(context.Context, *Empty) (*PluginDefinition, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDefinition not implemented")
}
func (UnimplementedPluginServer) Initialize(context.Context, *InitializeRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Initialize not implemented")
}
func (UnimplementedPluginServer) Start(context.Context, *Empty) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Start not implemented")
}
func (UnimplementedPluginServer) Stop(context.Context, *Empty) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Stop not implemented")
}
func (UnimplementedPluginServer) HandleEvent(context.Context, *PluginEvent) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method HandleEvent not implemented")
}
func (UnimplementedPluginServer) GetStatus(context.Context, *Empty) (*StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedPluginServer) GetConfig(context.Context, *Empty) (*ConfigJSON, error) {
	return nil, status.Error(codes.Unimplemented, "method GetConfig not implemented")
}
func (UnimplementedPluginServer) UpdateConfig(context.Context, *ConfigJSON) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateConfig not implemented")
}
func (UnimplementedPluginServer) GetCommands(context.Context, *Empty) (*CommandList, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCommands not implemented")
}
func (UnimplementedPluginServer) ExecuteCommand(context.Context, *ExecuteCommandRequest) (*CommandResult, error) {
	return nil, status.Error(codes.Unimplemented, "method ExecuteCommand not implemented")
}
func (UnimplementedPluginServer) GetCommandExecutionStatus(context.Context, *ExecutionIDRequest) (*CommandExecutionStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCommandExecutionStatus not implemented")
}
func (UnimplementedPluginServer) mustEmbedUnimplementedPluginServer() {}
func (UnimplementedPluginServer) testEmbeddedByValue()                {}

// UnsafePluginServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PluginServer will
// result in compilation errors.
type UnsafePluginServer interface {
	mustEmbedUnimplementedPluginServer()
}

func RegisterPluginServer(s grpc.ServiceRegistrar, srv PluginServer) {
	// If the following call panics, it indicates UnimplementedPluginServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Plugin_ServiceDesc, srv)
}

func _Plugin_GetDefinition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServer).GetDefinition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Plugin_GetDefinition_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServer).GetDefinition(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Plugin_Initialize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitializeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServer).Initialize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Plugin_Initialize_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServer).Initialize(ctx, req.(*InitializeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Plugin_Start_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServer).Start(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Plugin_Start_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServer).Start(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Plugin_Stop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServer).Stop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Plugin_Stop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServer).Stop(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Plugin_HandleEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PluginEvent)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServer).HandleEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Plugin_HandleEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServer).HandleEvent(ctx, req.(*PluginEvent))
	}
	return interceptor(ctx, in, info, handler)
}

func _Plugin_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Plugin_GetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServer).GetStatus(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Plugin_GetConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServer).GetConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Plugin_GetConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServer).GetConfig(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Plugin_UpdateConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigJSON)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServer).UpdateConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Plugin_UpdateConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServer).UpdateConfig(ctx, req.(*ConfigJSON))
	}
	return interceptor(ctx, in, info, handler)
}

func _Plugin_GetCommands_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServer).GetCommands(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Plugin_GetCommands_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServer).GetCommands(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Plugin_ExecuteCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteCommandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServer).ExecuteCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Plugin_ExecuteCommand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServer).ExecuteCommand(ctx, req.(*ExecuteCommandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Plugin_GetCommandExecutionStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecutionIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServer).GetCommandExecutionStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Plugin_GetCommandExecutionStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServer).GetCommandExecutionStatus(ctx, req.(*ExecutionIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Plugin_ServiceDesc is the grpc.ServiceDesc for Plugin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Plugin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "squadaegis.pluginrpc.v1.Plugin",
	HandlerType: (*PluginServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDefinition",
			Handler:    _Plugin_GetDefinition_Handler,
		},
		{
			MethodName: "Initialize",
			Handler:    _Plugin_Initialize_Handler,
		},
		{
			MethodName: "Start",
			Handler:    _Plugin_Start_Handler,
		},
		{
			MethodName: "Stop",
			Handler:    _Plugin_Stop_Handler,
		},
		{
			MethodName: "HandleEvent",
			Handler:    _Plugin_HandleEvent_Handler,
		},
		{
			MethodName: "GetStatus",
			Handler:    _Plugin_GetStatus_Handler,
		},
		{
			MethodName: "GetConfig",
			Handler:    _Plugin_GetConfig_Handler,
		},
		{
			MethodName: "UpdateConfig",
			Handler:    _Plugin_UpdateConfig_Handler,
		},
		{
			MethodName: "GetCommands",
			Handler:    _Plugin_GetCommands_Handler,
		},
		{
			MethodName: "ExecuteCommand",
			Handler:    _Plugin_ExecuteCommand_Handler,
		},
		{
			MethodName: "GetCommandExecutionStatus",
			Handler:    _Plugin_GetCommandExecutionStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/pluginrpc/proto/plugin.proto",
}
