// Squad Aegis native plugin wire protocol.
//
// The host invokes the Plugin service on the subprocess. Most fields whose
// shape is plugin-defined (config, command params, event data) travel as
// JSON-encoded bytes so the SDK can keep them as map[string]interface{} on
// either end without forcing every plugin to model a fixed proto schema.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: pkg/pluginrpc/proto/plugin.proto

package pluginrpcpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_pkg_pluginrpc_proto_plugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pluginrpc_proto_plugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_pkg_pluginrpc_proto_plugin_proto_rawDescGZIP(), []int{0}
}

type ConfigField struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Name        string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Required    bool                   `protobuf:"varint,3,opt,name=required,proto3" json:"required,omitempty"`
	Type        string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	// JSON-encoded default value; empty = no default.
	DefaultJson []byte `protobuf:"bytes,5,opt,name=default_json,json=defaultJson,proto3" json:"default_json,omitempty"`
	Sensitive   bool   `protobuf:"varint,6,opt,name=sensitive,proto3" json:"sensitive,omitempty"`
	// JSON-encoded list of options.
	OptionsJson   []byte         `protobuf:"bytes,7,opt,name=options_json,json=optionsJson,proto3" json:"options_json,omitempty"`
	Nested        []*ConfigField `protobuf:"bytes,8,rep,name=nested,proto3" json:"nested,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigField) Reset() {
	*x = ConfigField{}
	mi := &file_pkg_pluginrpc_proto_plugin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigField) ProtoMessage() {}

func (x *ConfigField) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pluginrpc_proto_plugin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigField.ProtoReflect.Descriptor instead.
func (*ConfigField) Descriptor() ([]byte, []int) {
	return file_pkg_pluginrpc_proto_plugin_proto_rawDescGZIP(), []int{1}
}

func (x *ConfigField) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ConfigField) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ConfigField) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

func (x *ConfigField) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ConfigField) GetDefaultJson() []byte {
	if x != nil {
		return x.DefaultJson
	}
	return nil
}

func (x *ConfigField) GetSensitive() bool {
	if x != nil {
		return x.Sensitive
	}
	return false
}

func (x *ConfigField) GetOptionsJson() []byte {
	if x != nil {
		return x.OptionsJson
	}
	return nil
}

func (x *ConfigField) GetNested() []*ConfigField {
	if x != nil {
		return x.Nested
	}
	return nil
}

type ConfigSchema struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fields        []*ConfigField         `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigSchema) Reset() {
	*x = ConfigSchema{}
	mi := &file_pkg_pluginrpc_proto_plugin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigSchema) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigSchema) ProtoMessage() {}

func (x *ConfigSchema) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pluginrpc_proto_plugin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigSchema.ProtoReflect.Descriptor instead.
func (*ConfigSchema) Descriptor() ([]byte, []int) {
	return file_pkg_pluginrpc_proto_plugin_proto_rawDescGZIP(), []int{2}
}

func (x *ConfigSchema) GetFields() []*ConfigField {
	if x != nil {
		return x.Fields
	}
	return nil
}

type PluginDefinition struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	PluginId               string                 `protobuf:"bytes,1,opt,name=plugin_id,json=pluginId,proto3" json:"plugin_id,omitempty"`
	AllowMultipleInstances bool                   `protobuf:"varint,2,opt,name=allow_multiple_instances,json=allowMultipleInstances,proto3" json:"allow_multiple_instances,omitempty"`
	LongRunning            bool                   `protobuf:"varint,3,opt,name=long_running,json=longRunning,proto3" json:"long_running,omitempty"`
	RequiredConnectors     []string               `protobuf:"bytes,4,rep,name=required_connectors,json=requiredConnectors,proto3" json:"required_connectors,omitempty"`
	OptionalConnectors     []string               `protobuf:"bytes,5,rep,name=optional_connectors,json=optionalConnectors,proto3" json:"optional_connectors,omitempty"`
	ConfigSchema           *ConfigSchema          `protobuf:"bytes,6,opt,name=config_schema,json=configSchema,proto3" json:"config_schema,omitempty"`
	Events                 []string               `protobuf:"bytes,7,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *PluginDefinition) Reset() {
	*x = PluginDefinition{}
	mi := &file_pkg_pluginrpc_proto_plugin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginDefinition) ProtoMessage() {}

func (x *PluginDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pluginrpc_proto_plugin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginDefinition.ProtoReflect.Descriptor instead.
func (*PluginDefinition) Descriptor() ([]byte, []int) {
	return file_pkg_pluginrpc_proto_plugin_proto_rawDescGZIP(), []int{3}
}

func (x *PluginDefinition) GetPluginId() string {
	if x != nil {
		return x.PluginId
	}
	return ""
}

func (x *PluginDefinition) GetAllowMultipleInstances() bool {
	if x != nil {
		return x.AllowMultipleInstances
	}
	return false
}

func (x *PluginDefinition) GetLongRunning() bool {
	if x != nil {
		return x.LongRunning
	}
	return false
}

func (x *PluginDefinition) GetRequiredConnectors() []string {
	if x != nil {
		return x.RequiredConnectors
	}
	return nil
}

func (x *PluginDefinition) GetOptionalConnectors() []string {
	if x != nil {
		return x.OptionalConnectors
	}
	return nil
}

func (x *PluginDefinition) GetConfigSchema() *ConfigSchema {
	if x != nil {
		return x.ConfigSchema
	}
	return nil
}

func (x *PluginDefinition) GetEvents() []string {
	if x != nil {
		return x.Events
	}
	return nil
}

type InitializeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// JSON-encoded config map.
	ConfigJson []byte `protobuf:"bytes,1,opt,name=config_json,json=configJson,proto3" json:"config_json,omitempty"`
	// Broker ID the plugin should dial back into for the HostAPI service.
	HostApiBrokerId uint32 `protobuf:"varint,2,opt,name=host_api_broker_id,json=hostApiBrokerId,proto3" json:"host_api_broker_id,omitempty"`
	InstanceId      string `protobuf:"bytes,3,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	ServerId        string `protobuf:"bytes,4,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	LogLevel        string `protobuf:"bytes,5,opt,name=log_level,json=logLevel,proto3" json:"log_level,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *InitializeRequest) Reset() {
	*x = InitializeRequest{}
	mi := &file_pkg_pluginrpc_proto_plugin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitializeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitializeRequest) ProtoMessage() {}

func (x *InitializeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pluginrpc_proto_plugin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitializeRequest.ProtoReflect.Descriptor instead.
func (*InitializeRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pluginrpc_proto_plugin_proto_rawDescGZIP(), []int{4}
}

func (x *InitializeRequest) GetConfigJson() []byte {
	if x != nil {
		return x.ConfigJson
	}
	return nil
}

func (x *InitializeRequest) GetHostApiBrokerId() uint32 {
	if x != nil {
		return x.HostApiBrokerId
	}
	return 0
}

func (x *InitializeRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *InitializeRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *InitializeRequest) GetLogLevel() string {
	if x != nil {
		return x.LogLevel
	}
	return ""
}

type PluginEvent struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Id       string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ServerId string                 `protobuf:"bytes,2,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	Source   string                 `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	Type     string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	// JSON-encoded event-specific data; empty means no data.
	DataJson      []byte                 `protobuf:"bytes,5,opt,name=data_json,json=dataJson,proto3" json:"data_json,omitempty"`
	Raw           string                 `protobuf:"bytes,6,opt,name=raw,proto3" json:"raw,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginEvent) Reset() {
	*x = PluginEvent{}
	mi := &file_pkg_pluginrpc_proto_plugin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginEvent) ProtoMessage() {}

func (x *PluginEvent) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pluginrpc_proto_plugin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginEvent.ProtoReflect.Descriptor instead.
func (*PluginEvent) Descriptor() ([]byte, []int) {
	return file_pkg_pluginrpc_proto_plugin_proto_rawDescGZIP(), []int{5}
}

func (x *PluginEvent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PluginEvent) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *PluginEvent) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *PluginEvent) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *PluginEvent) GetDataJson() []byte {
	if x != nil {
		return x.DataJson
	}
	return nil
}

func (x *PluginEvent) GetRaw() string {
	if x != nil {
		return x.Raw
	}
	return ""
}

func (x *PluginEvent) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type StatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_pkg_pluginrpc_proto_plugin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pluginrpc_proto_plugin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pluginrpc_proto_plugin_proto_rawDescGZIP(), []int{6}
}

func (x *StatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// ConfigJSON wraps a JSON-encoded map[string]interface{} so plugin authors
// can keep working with arbitrary config shapes.
type ConfigJSON struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConfigJson    []byte                 `protobuf:"bytes,1,opt,name=config_json,json=configJson,proto3" json:"config_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigJSON) Reset() {
	*x = ConfigJSON{}
	mi := &file_pkg_pluginrpc_proto_plugin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigJSON) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigJSON) ProtoMessage() {}

func (x *ConfigJSON) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pluginrpc_proto_plugin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigJSON.ProtoReflect.Descriptor instead.
func (*ConfigJSON) Descriptor() ([]byte, []int) {
	return file_pkg_pluginrpc_proto_plugin_proto_rawDescGZIP(), []int{7}
}

func (x *ConfigJSON) GetConfigJson() []byte {
	if x != nil {
		return x.ConfigJson
	}
	return nil
}

type CommandList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Commands      []*PluginCommand       `protobuf:"bytes,1,rep,name=commands,proto3" json:"commands,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandList) Reset() {
	*x = CommandList{}
	mi := &file_pkg_pluginrpc_proto_plugin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandList) ProtoMessage() {}

func (x *CommandList) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pluginrpc_proto_plugin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandList.ProtoReflect.Descriptor instead.
func (*CommandList) Descriptor() ([]byte, []int) {
	return file_pkg_pluginrpc_proto_plugin_proto_rawDescGZIP(), []int{8}
}

func (x *CommandList) GetCommands() []*PluginCommand {
	if x != nil {
		return x.Commands
	}
	return nil
}

type PluginCommand struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description         string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Category            string                 `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	Parameters          *ConfigSchema          `protobuf:"bytes,5,opt,name=parameters,proto3" json:"parameters,omitempty"`
	ExecutionType       string                 `protobuf:"bytes,6,opt,name=execution_type,json=executionType,proto3" json:"execution_type,omitempty"`
	RequiredPermissions []string               `protobuf:"bytes,7,rep,name=required_permissions,json=requiredPermissions,proto3" json:"required_permissions,omitempty"`
	ConfirmMessage      string                 `protobuf:"bytes,8,opt,name=confirm_message,json=confirmMessage,proto3" json:"confirm_message,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *PluginCommand) Reset() {
	*x = PluginCommand{}
	mi := &file_pkg_pluginrpc_proto_plugin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginCommand) ProtoMessage() {}

func (x *PluginCommand) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pluginrpc_proto_plugin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginCommand.ProtoReflect.Descriptor instead.
func (*PluginCommand) Descriptor() ([]byte, []int) {
	return file_pkg_pluginrpc_proto_plugin_proto_rawDescGZIP(), []int{9}
}

func (x *PluginCommand) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PluginCommand) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PluginCommand) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PluginCommand) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *PluginCommand) GetParameters() *ConfigSchema {
	if x != nil {
		return x.Parameters
	}
	return nil
}

func (x *PluginCommand) GetExecutionType() string {
	if x != nil {
		return x.ExecutionType
	}
	return ""
}

func (x *PluginCommand) GetRequiredPermissions() []string {
	if x != nil {
		return x.RequiredPermissions
	}
	return nil
}

func (x *PluginCommand) GetConfirmMessage() string {
	if x != nil {
		return x.ConfirmMessage
	}
	return ""
}

type ExecuteCommandRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	CommandId string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	// JSON-encoded params map.
	ParamsJson    []byte `protobuf:"bytes,2,opt,name=params_json,json=paramsJson,proto3" json:"params_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteCommandRequest) Reset() {
	*x = ExecuteCommandRequest{}
	mi := &file_pkg_pluginrpc_proto_plugin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteCommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteCommandRequest) ProtoMessage() {}

func (x *ExecuteCommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pluginrpc_proto_plugin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteCommandRequest.ProtoReflect.Descriptor instead.
func (*ExecuteCommandRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pluginrpc_proto_plugin_proto_rawDescGZIP(), []int{10}
}

func (x *ExecuteCommandRequest) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *ExecuteCommandRequest) GetParamsJson() []byte {
	if x != nil {
		return x.ParamsJson
	}
	return nil
}

type CommandResult struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Success bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// JSON-encoded data map.
	DataJson      []byte `protobuf:"bytes,3,opt,name=data_json,json=dataJson,proto3" json:"data_json,omitempty"`
	ExecutionId   string `protobuf:"bytes,4,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	Error         string `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandResult) Reset() {
	*x = CommandResult{}
	mi := &file_pkg_pluginrpc_proto_plugin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandResult) ProtoMessage() {}

func (x *CommandResult) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pluginrpc_proto_plugin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandResult.ProtoReflect.Descriptor instead.
func (*CommandResult) Descriptor() ([]byte, []int) {
	return file_pkg_pluginrpc_proto_plugin_proto_rawDescGZIP(), []int{11}
}

func (x *CommandResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CommandResult) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CommandResult) GetDataJson() []byte {
	if x != nil {
		return x.DataJson
	}
	return nil
}

func (x *CommandResult) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *CommandResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ExecutionIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId   string                 `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecutionIDRequest) Reset() {
	*x = ExecutionIDRequest{}
	mi := &file_pkg_pluginrpc_proto_plugin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionIDRequest) ProtoMessage() {}

func (x *ExecutionIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pluginrpc_proto_plugin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionIDRequest.ProtoReflect.Descriptor instead.
func (*ExecutionIDRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pluginrpc_proto_plugin_proto_rawDescGZIP(), []int{12}
}

func (x *ExecutionIDRequest) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

type CommandExecutionStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId   string                 `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	CommandId     string                 `protobuf:"bytes,2,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Progress      int32                  `protobuf:"varint,4,opt,name=progress,proto3" json:"progress,omitempty"`
	Message       string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	Result        *CommandResult         `protobuf:"bytes,6,opt,name=result,proto3" json:"result,omitempty"`
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	CompletedAt   *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandExecutionStatus) Reset() {
	*x = CommandExecutionStatus{}
	mi := &file_pkg_pluginrpc_proto_plugin_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandExecutionStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandExecutionStatus) ProtoMessage() {}

func (x *CommandExecutionStatus) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pluginrpc_proto_plugin_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandExecutionStatus.ProtoReflect.Descriptor instead.
func (*CommandExecutionStatus) Descriptor() ([]byte, []int) {
	return file_pkg_pluginrpc_proto_plugin_proto_rawDescGZIP(), []int{13}
}

func (x *CommandExecutionStatus) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *CommandExecutionStatus) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *CommandExecutionStatus) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CommandExecutionStatus) GetProgress() int32 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *CommandExecutionStatus) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CommandExecutionStatus) GetResult() *CommandResult {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *CommandExecutionStatus) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *CommandExecutionStatus) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

var File_pkg_pluginrpc_proto_plugin_proto protoreflect.FileDescriptor

const file_pkg_pluginrpc_proto_plugin_proto_rawDesc = "" +
	"\n" +
	" pkg/pluginrpc/proto/plugin.proto\x12\x17squadaegis.pluginrpc.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\a\n" +
	"\x05Empty\"\x95\x02\n" +
	"\vConfigField\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1a\n" +
	"\brequired\x18\x03 \x01(\bR\brequired\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12!\n" +
	"\fdefault_json\x18\x05 \x01(\fR\vdefaultJson\x12\x1c\n" +
	"\tsensitive\x18\x06 \x01(\bR\tsensitive\x12!\n" +
	"\foptions_json\x18\a \x01(\fR\voptionsJson\x12<\n" +
	"\x06nested\x18\b \x03(\v2$.squadaegis.pluginrpc.v1.ConfigFieldR\x06nested\"L\n" +
	"\fConfigSchema\x12<\n" +
	"\x06fields\x18\x01 \x03(\v2$.squadaegis.pluginrpc.v1.ConfigFieldR\x06fields\"\xd2\x02\n" +
	"\x10PluginDefinition\x12\x1b\n" +
	"\tplugin_id\x18\x01 \x01(\tR\bpluginId\x128\n" +
	"\x18allow_multiple_instances\x18\x02 \x01(\bR\x16allowMultipleInstances\x12!\n" +
	"\flong_running\x18\x03 \x01(\bR\vlongRunning\x12/\n" +
	"\x13required_connectors\x18\x04 \x03(\tR\x12requiredConnectors\x12/\n" +
	"\x13optional_connectors\x18\x05 \x03(\tR\x12optionalConnectors\x12J\n" +
	"\rconfig_schema\x18\x06 \x01(\v2%.squadaegis.pluginrpc.v1.ConfigSchemaR\fconfigSchema\x12\x16\n" +
	"\x06events\x18\a \x03(\tR\x06events\"\xbc\x01\n" +
	"\x11InitializeRequest\x12\x1f\n" +
	"\vconfig_json\x18\x01 \x01(\fR\n" +
	"configJson\x12+\n" +
	"\x12host_api_broker_id\x18\x02 \x01(\rR\x0fhostApiBrokerId\x12\x1f\n" +
	"\vinstance_id\x18\x03 \x01(\tR\n" +
	"instanceId\x12\x1b\n" +
	"\tserver_id\x18\x04 \x01(\tR\bserverId\x12\x1b\n" +
	"\tlog_level\x18\x05 \x01(\tR\blogLevel\"\xcf\x01\n" +
	"\vPluginEvent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tserver_id\x18\x02 \x01(\tR\bserverId\x12\x16\n" +
	"\x06source\x18\x03 \x01(\tR\x06source\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x1b\n" +
	"\tdata_json\x18\x05 \x01(\fR\bdataJson\x12\x10\n" +
	"\x03raw\x18\x06 \x01(\tR\x03raw\x128\n" +
	"\ttimestamp\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"(\n" +
	"\x0eStatusResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"-\n" +
	"\n" +
	"ConfigJSON\x12\x1f\n" +
	"\vconfig_json\x18\x01 \x01(\fR\n" +
	"configJson\"Q\n" +
	"\vCommandList\x12B\n" +
	"\bcommands\x18\x01 \x03(\v2&.squadaegis.pluginrpc.v1.PluginCommandR\bcommands\"\xbb\x02\n" +
	"\rPluginCommand\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1a\n" +
	"\bcategory\x18\x04 \x01(\tR\bcategory\x12E\n" +
	"\n" +
	"parameters\x18\x05 \x01(\v2%.squadaegis.pluginrpc.v1.ConfigSchemaR\n" +
	"parameters\x12%\n" +
	"\x0eexecution_type\x18\x06 \x01(\tR\rexecutionType\x121\n" +
	"\x14required_permissions\x18\a \x03(\tR\x13requiredPermissions\x12'\n" +
	"\x0fconfirm_message\x18\b \x01(\tR\x0econfirmMessage\"W\n" +
	"\x15ExecuteCommandRequest\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12\x1f\n" +
	"\vparams_json\x18\x02 \x01(\fR\n" +
	"paramsJson\"\x99\x01\n" +
	"\rCommandResult\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1b\n" +
	"\tdata_json\x18\x03 \x01(\fR\bdataJson\x12!\n" +
	"\fexecution_id\x18\x04 \x01(\tR\vexecutionId\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\"7\n" +
	"\x12ExecutionIDRequest\x12!\n" +
	"\fexecution_id\x18\x01 \x01(\tR\vexecutionId\"\xe2\x02\n" +
	"\x16CommandExecutionStatus\x12!\n" +
	"\fexecution_id\x18\x01 \x01(\tR\vexecutionId\x12\x1d\n" +
	"\n" +
	"command_id\x18\x02 \x01(\tR\tcommandId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x1a\n" +
	"\bprogress\x18\x04 \x01(\x05R\bprogress\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\x12>\n" +
	"\x06result\x18\x06 \x01(\v2&.squadaegis.pluginrpc.v1.CommandResultR\x06result\x129\n" +
	"\n" +
	"started_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12=\n" +
	"\fcompleted_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt2\xdb\a\n" +
	"\x06Plugin\x12Z\n" +
	"\rGetDefinition\x12\x1e.squadaegis.pluginrpc.v1.Empty\x1a).squadaegis.pluginrpc.v1.PluginDefinition\x12X\n" +
	"\n" +
	"Initialize\x12*.squadaegis.pluginrpc.v1.InitializeRequest\x1a\x1e.squadaegis.pluginrpc.v1.Empty\x12G\n" +
	"\x05Start\x12\x1e.squadaegis.pluginrpc.v1.Empty\x1a\x1e.squadaegis.pluginrpc.v1.Empty\x12F\n" +
	"\x04Stop\x12\x1e.squadaegis.pluginrpc.v1.Empty\x1a\x1e.squadaegis.pluginrpc.v1.Empty\x12S\n" +
	"\vHandleEvent\x12$.squadaegis.pluginrpc.v1.PluginEvent\x1a\x1e.squadaegis.pluginrpc.v1.Empty\x12T\n" +
	"\tGetStatus\x12\x1e.squadaegis.pluginrpc.v1.Empty\x1a'.squadaegis.pluginrpc.v1.StatusResponse\x12P\n" +
	"\tGetConfig\x12\x1e.squadaegis.pluginrpc.v1.Empty\x1a#.squadaegis.pluginrpc.v1.ConfigJSON\x12S\n" +
	"\fUpdateConfig\x12#.squadaegis.pluginrpc.v1.ConfigJSON\x1a\x1e.squadaegis.pluginrpc.v1.Empty\x12S\n" +
	"\vGetCommands\x12\x1e.squadaegis.pluginrpc.v1.Empty\x1a$.squadaegis.pluginrpc.v1.CommandList\x12h\n" +
	"\x0eExecuteCommand\x12..squadaegis.pluginrpc.v1.ExecuteCommandRequest\x1a&.squadaegis.pluginrpc.v1.CommandResult\x12y\n" +
	"\x19GetCommandExecutionStatus\x12+.squadaegis.pluginrpc.v1.ExecutionIDRequest\x1a/.squadaegis.pluginrpc.v1.CommandExecutionStatusB?Z=go.codycody31.dev/squad-aegis/pkg/pluginrpc/proto;pluginrpcpbb\x06proto3"

var (
	file_pkg_pluginrpc_proto_plugin_proto_rawDescOnce sync.Once
	file_pkg_pluginrpc_proto_plugin_proto_rawDescData []byte
)

func file_pkg_pluginrpc_proto_plugin_proto_rawDescGZIP() []byte {
	file_pkg_pluginrpc_proto_plugin_proto_rawDescOnce.Do(func() {
		file_pkg_pluginrpc_proto_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_pluginrpc_proto_plugin_proto_rawDesc), len(file_pkg_pluginrpc_proto_plugin_proto_rawDesc)))
	})
	return file_pkg_pluginrpc_proto_plugin_proto_rawDescData
}

var file_pkg_pluginrpc_proto_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_pkg_pluginrpc_proto_plugin_proto_goTypes = []any{
	(*Empty)(nil),                  // 0: squadaegis.pluginrpc.v1.Empty
	(*ConfigField)(nil),            // 1: squadaegis.pluginrpc.v1.ConfigField
	(*ConfigSchema)(nil),           // 2: squadaegis.pluginrpc.v1.ConfigSchema
	(*PluginDefinition)(nil),       // 3: squadaegis.pluginrpc.v1.PluginDefinition
	(*InitializeRequest)(nil),      // 4: squadaegis.pluginrpc.v1.InitializeRequest
	(*PluginEvent)(nil),            // 5: squadaegis.pluginrpc.v1.PluginEvent
	(*StatusResponse)(nil),         // 6: squadaegis.pluginrpc.v1.StatusResponse
	(*ConfigJSON)(nil),             // 7: squadaegis.pluginrpc.v1.ConfigJSON
	(*CommandList)(nil),            // 8: squadaegis.pluginrpc.v1.CommandList
	(*PluginCommand)(nil),          // 9: squadaegis.pluginrpc.v1.PluginCommand
	(*ExecuteCommandRequest)(nil),  // 10: squadaegis.pluginrpc.v1.ExecuteCommandRequest
	(*CommandResult)(nil),          // 11: squadaegis.pluginrpc.v1.CommandResult
	(*ExecutionIDRequest)(nil),     // 12: squadaegis.pluginrpc.v1.ExecutionIDRequest
	(*CommandExecutionStatus)(nil), // 13: squadaegis.pluginrpc.v1.CommandExecutionStatus
	(*timestamppb.Timestamp)(nil),  // 14: google.protobuf.Timestamp
}
var file_pkg_pluginrpc_proto_plugin_proto_depIdxs = []int32{
	1,  // 0: squadaegis.pluginrpc.v1.ConfigField.nested:type_name -> squadaegis.pluginrpc.v1.ConfigField
	1,  // 1: squadaegis.pluginrpc.v1.ConfigSchema.fields:type_name -> squadaegis.pluginrpc.v1.ConfigField
	2,  // 2: squadaegis.pluginrpc.v1.PluginDefinition.config_schema:type_name -> squadaegis.pluginrpc.v1.ConfigSchema
	14, // 3: squadaegis.pluginrpc.v1.PluginEvent.timestamp:type_name -> google.protobuf.Timestamp
	9,  // 4: squadaegis.pluginrpc.v1.CommandList.commands:type_name -> squadaegis.pluginrpc.v1.PluginCommand
	2,  // 5: squadaegis.pluginrpc.v1.PluginCommand.parameters:type_name -> squadaegis.pluginrpc.v1.ConfigSchema
	11, // 6: squadaegis.pluginrpc.v1.CommandExecutionStatus.result:type_name -> squadaegis.pluginrpc.v1.CommandResult
	14, // 7: squadaegis.pluginrpc.v1.CommandExecutionStatus.started_at:type_name -> google.protobuf.Timestamp
	14, // 8: squadaegis.pluginrpc.v1.CommandExecutionStatus.completed_at:type_name -> google.protobuf.Timestamp
	0,  // 9: squadaegis.pluginrpc.v1.Plugin.GetDefinition:input_type -> squadaegis.pluginrpc.v1.Empty
	4,  // 10: squadaegis.pluginrpc.v1.Plugin.Initialize:input_type -> squadaegis.pluginrpc.v1.InitializeRequest
	0,  // 11: squadaegis.pluginrpc.v1.Plugin.Start:input_type -> squadaegis.pluginrpc.v1.Empty
	0,  // 12: squadaegis.pluginrpc.v1.Plugin.Stop:input_type -> squadaegis.pluginrpc.v1.Empty
	5,  // 13: squadaegis.pluginrpc.v1.Plugin.HandleEvent:input_type -> squadaegis.pluginrpc.v1.PluginEvent
	0,  // 14: squadaegis.pluginrpc.v1.Plugin.GetStatus:input_type -> squadaegis.pluginrpc.v1.Empty
	0,  // 15: squadaegis.pluginrpc.v1.Plugin.GetConfig:input_type -> squadaegis.pluginrpc.v1.Empty
	7,  // 16: squadaegis.pluginrpc.v1.Plugin.UpdateConfig:input_type -> squadaegis.pluginrpc.v1.ConfigJSON
	0,  // 17: squadaegis.pluginrpc.v1.Plugin.GetCommands:input_type -> squadaegis.pluginrpc.v1.Empty
	10, // 18: squadaegis.pluginrpc.v1.Plugin.ExecuteCommand:input_type -> squadaegis.pluginrpc.v1.ExecuteCommandRequest
	12, // 19: squadaegis.pluginrpc.v1.Plugin.GetCommandExecutionStatus:input_type -> squadaegis.pluginrpc.v1.ExecutionIDRequest
	3,  // 20: squadaegis.pluginrpc.v1.Plugin.GetDefinition:output_type -> squadaegis.pluginrpc.v1.PluginDefinition
	0,  // 21: squadaegis.pluginrpc.v1.Plugin.Initialize:output_type -> squadaegis.pluginrpc.v1.Empty
	0,  // 22: squadaegis.pluginrpc.v1.Plugin.Start:output_type -> squadaegis.pluginrpc.v1.Empty
	0,  // 23: squadaegis.pluginrpc.v1.Plugin.Stop:output_type -> squadaegis.pluginrpc.v1.Empty
	0,  // 24: squadaegis.pluginrpc.v1.Plugin.HandleEvent:output_type -> squadaegis.pluginrpc.v1.Empty
	6,  // 25: squadaegis.pluginrpc.v1.Plugin.GetStatus:output_type -> squadaegis.pluginrpc.v1.StatusResponse
	7,  // 26: squadaegis.pluginrpc.v1.Plugin.GetConfig:output_type -> squadaegis.pluginrpc.v1.ConfigJSON
	0,  // 27: squadaegis.pluginrpc.v1.Plugin.UpdateConfig:output_type -> squadaegis.pluginrpc.v1.Empty
	8,  // 28: squadaegis.pluginrpc.v1.Plugin.GetCommands:output_type -> squadaegis.pluginrpc.v1.CommandList
	11, // 29: squadaegis.pluginrpc.v1.Plugin.ExecuteCommand:output_type -> squadaegis.pluginrpc.v1.CommandResult
	13, // 30: squadaegis.pluginrpc.v1.Plugin.GetCommandExecutionStatus:output_type -> squadaegis.pluginrpc.v1.CommandExecutionStatus
	20, // [20:31] is the sub-list for method output_type
	9,  // [9:20] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_pkg_pluginrpc_proto_plugin_proto_init() }
func file_pkg_pluginrpc_proto_plugin_proto_init() {
	if File_pkg_pluginrpc_proto_plugin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_pluginrpc_proto_plugin_proto_rawDesc), len(file_pkg_pluginrpc_proto_plugin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_pluginrpc_proto_plugin_proto_goTypes,
		DependencyIndexes: file_pkg_pluginrpc_proto_plugin_proto_depIdxs,
		MessageInfos:      file_pkg_pluginrpc_proto_plugin_proto_msgTypes,
	}.Build()
	File_pkg_pluginrpc_proto_plugin_proto = out.File
	file_pkg_pluginrpc_proto_plugin_proto_goTypes = nil
	file_pkg_pluginrpc_proto_plugin_proto_depIdxs = nil
}
