// Squad Aegis native connector wire protocol.
//
// The host invokes the Connector service on the subprocess. Arbitrary-shape
// data (config, invoke envelopes) travels as JSON-encoded bytes so the SDK
// can keep the plugin-facing API as map[string]interface{}.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: pkg/connectorrpc/proto/connector.proto

package connectorrpcpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_pkg_connectorrpc_proto_connector_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_connectorrpc_proto_connector_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_pkg_connectorrpc_proto_connector_proto_rawDescGZIP(), []int{0}
}

type ConfigField struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Required      bool                   `protobuf:"varint,3,opt,name=required,proto3" json:"required,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	DefaultJson   []byte                 `protobuf:"bytes,5,opt,name=default_json,json=defaultJson,proto3" json:"default_json,omitempty"`
	Sensitive     bool                   `protobuf:"varint,6,opt,name=sensitive,proto3" json:"sensitive,omitempty"`
	OptionsJson   []byte                 `protobuf:"bytes,7,opt,name=options_json,json=optionsJson,proto3" json:"options_json,omitempty"`
	Nested        []*ConfigField         `protobuf:"bytes,8,rep,name=nested,proto3" json:"nested,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigField) Reset() {
	*x = ConfigField{}
	mi := &file_pkg_connectorrpc_proto_connector_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigField) ProtoMessage() {}

func (x *ConfigField) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_connectorrpc_proto_connector_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigField.ProtoReflect.Descriptor instead.
func (*ConfigField) Descriptor() ([]byte, []int) {
	return file_pkg_connectorrpc_proto_connector_proto_rawDescGZIP(), []int{1}
}

func (x *ConfigField) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ConfigField) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ConfigField) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

func (x *ConfigField) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ConfigField) GetDefaultJson() []byte {
	if x != nil {
		return x.DefaultJson
	}
	return nil
}

func (x *ConfigField) GetSensitive() bool {
	if x != nil {
		return x.Sensitive
	}
	return false
}

func (x *ConfigField) GetOptionsJson() []byte {
	if x != nil {
		return x.OptionsJson
	}
	return nil
}

func (x *ConfigField) GetNested() []*ConfigField {
	if x != nil {
		return x.Nested
	}
	return nil
}

type ConfigSchema struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fields        []*ConfigField         `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigSchema) Reset() {
	*x = ConfigSchema{}
	mi := &file_pkg_connectorrpc_proto_connector_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigSchema) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigSchema) ProtoMessage() {}

func (x *ConfigSchema) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_connectorrpc_proto_connector_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigSchema.ProtoReflect.Descriptor instead.
func (*ConfigSchema) Descriptor() ([]byte, []int) {
	return file_pkg_connectorrpc_proto_connector_proto_rawDescGZIP(), []int{2}
}

func (x *ConfigSchema) GetFields() []*ConfigField {
	if x != nil {
		return x.Fields
	}
	return nil
}

type ConnectorDefinition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConnectorId   string                 `protobuf:"bytes,1,opt,name=connector_id,json=connectorId,proto3" json:"connector_id,omitempty"`
	ConfigSchema  *ConfigSchema          `protobuf:"bytes,2,opt,name=config_schema,json=configSchema,proto3" json:"config_schema,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectorDefinition) Reset() {
	*x = ConnectorDefinition{}
	mi := &file_pkg_connectorrpc_proto_connector_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectorDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectorDefinition) ProtoMessage() {}

func (x *ConnectorDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_connectorrpc_proto_connector_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectorDefinition.ProtoReflect.Descriptor instead.
func (*ConnectorDefinition) Descriptor() ([]byte, []int) {
	return file_pkg_connectorrpc_proto_connector_proto_rawDescGZIP(), []int{3}
}

func (x *ConnectorDefinition) GetConnectorId() string {
	if x != nil {
		return x.ConnectorId
	}
	return ""
}

func (x *ConnectorDefinition) GetConfigSchema() *ConfigSchema {
	if x != nil {
		return x.ConfigSchema
	}
	return nil
}

type InitializeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// JSON-encoded config map.
	ConfigJson    []byte `protobuf:"bytes,1,opt,name=config_json,json=configJson,proto3" json:"config_json,omitempty"`
	InstanceId    string `protobuf:"bytes,2,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitializeRequest) Reset() {
	*x = InitializeRequest{}
	mi := &file_pkg_connectorrpc_proto_connector_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitializeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitializeRequest) ProtoMessage() {}

func (x *InitializeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_connectorrpc_proto_connector_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitializeRequest.ProtoReflect.Descriptor instead.
func (*InitializeRequest) Descriptor() ([]byte, []int) {
	return file_pkg_connectorrpc_proto_connector_proto_rawDescGZIP(), []int{4}
}

func (x *InitializeRequest) GetConfigJson() []byte {
	if x != nil {
		return x.ConfigJson
	}
	return nil
}

func (x *InitializeRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

type StatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_pkg_connectorrpc_proto_connector_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_connectorrpc_proto_connector_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_pkg_connectorrpc_proto_connector_proto_rawDescGZIP(), []int{5}
}

func (x *StatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ConfigJSON struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConfigJson    []byte                 `protobuf:"bytes,1,opt,name=config_json,json=configJson,proto3" json:"config_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigJSON) Reset() {
	*x = ConfigJSON{}
	mi := &file_pkg_connectorrpc_proto_connector_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigJSON) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigJSON) ProtoMessage() {}

func (x *ConfigJSON) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_connectorrpc_proto_connector_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigJSON.ProtoReflect.Descriptor instead.
func (*ConfigJSON) Descriptor() ([]byte, []int) {
	return file_pkg_connectorrpc_proto_connector_proto_rawDescGZIP(), []int{6}
}

func (x *ConfigJSON) GetConfigJson() []byte {
	if x != nil {
		return x.ConfigJson
	}
	return nil
}

type InvokeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	V     string                 `protobuf:"bytes,1,opt,name=v,proto3" json:"v,omitempty"`
	// JSON-encoded data map.
	DataJson      []byte `protobuf:"bytes,2,opt,name=data_json,json=dataJson,proto3" json:"data_json,omitempty"`
	TimeoutMs     int64  `protobuf:"varint,3,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvokeRequest) Reset() {
	*x = InvokeRequest{}
	mi := &file_pkg_connectorrpc_proto_connector_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeRequest) ProtoMessage() {}

func (x *InvokeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_connectorrpc_proto_connector_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeRequest.ProtoReflect.Descriptor instead.
func (*InvokeRequest) Descriptor() ([]byte, []int) {
	return file_pkg_connectorrpc_proto_connector_proto_rawDescGZIP(), []int{7}
}

func (x *InvokeRequest) GetV() string {
	if x != nil {
		return x.V
	}
	return ""
}

func (x *InvokeRequest) GetDataJson() []byte {
	if x != nil {
		return x.DataJson
	}
	return nil
}

func (x *InvokeRequest) GetTimeoutMs() int64 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

type InvokeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	V     string                 `protobuf:"bytes,1,opt,name=v,proto3" json:"v,omitempty"`
	Ok    bool                   `protobuf:"varint,2,opt,name=ok,proto3" json:"ok,omitempty"`
	// JSON-encoded data map.
	DataJson      []byte `protobuf:"bytes,3,opt,name=data_json,json=dataJson,proto3" json:"data_json,omitempty"`
	Error         string `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvokeResponse) Reset() {
	*x = InvokeResponse{}
	mi := &file_pkg_connectorrpc_proto_connector_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeResponse) ProtoMessage() {}

func (x *InvokeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_connectorrpc_proto_connector_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeResponse.ProtoReflect.Descriptor instead.
func (*InvokeResponse) Descriptor() ([]byte, []int) {
	return file_pkg_connectorrpc_proto_connector_proto_rawDescGZIP(), []int{8}
}

func (x *InvokeResponse) GetV() string {
	if x != nil {
		return x.V
	}
	return ""
}

func (x *InvokeResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *InvokeResponse) GetDataJson() []byte {
	if x != nil {
		return x.DataJson
	}
	return nil
}

func (x *InvokeResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_pkg_connectorrpc_proto_connector_proto protoreflect.FileDescriptor

const file_pkg_connectorrpc_proto_connector_proto_rawDesc = "" +
	"\n" +
	"&pkg/connectorrpc/proto/connector.proto\x12\x1asquadaegis.connectorrpc.v1\"\a\n" +
	"\x05Empty\"\x98\x02\n" +
	"\vConfigField\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1a\n" +
	"\brequired\x18\x03 \x01(\bR\brequired\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12!\n" +
	"\fdefault_json\x18\x05 \x01(\fR\vdefaultJson\x12\x1c\n" +
	"\tsensitive\x18\x06 \x01(\bR\tsensitive\x12!\n" +
	"\foptions_json\x18\a \x01(\fR\voptionsJson\x12?\n" +
	"\x06nested\x18\b \x03(\v2'.squadaegis.connectorrpc.v1.ConfigFieldR\x06nested\"O\n" +
	"\fConfigSchema\x12?\n" +
	"\x06fields\x18\x01 \x03(\v2'.squadaegis.connectorrpc.v1.ConfigFieldR\x06fields\"\x87\x01\n" +
	"\x13ConnectorDefinition\x12!\n" +
	"\fconnector_id\x18\x01 \x01(\tR\vconnectorId\x12M\n" +
	"\rconfig_schema\x18\x02 \x01(\v2(.squadaegis.connectorrpc.v1.ConfigSchemaR\fconfigSchema\"U\n" +
	"\x11InitializeRequest\x12\x1f\n" +
	"\vconfig_json\x18\x01 \x01(\fR\n" +
	"configJson\x12\x1f\n" +
	"\vinstance_id\x18\x02 \x01(\tR\n" +
	"instanceId\"(\n" +
	"\x0eStatusResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"-\n" +
	"\n" +
	"ConfigJSON\x12\x1f\n" +
	"\vconfig_json\x18\x01 \x01(\fR\n" +
	"configJson\"Y\n" +
	"\rInvokeRequest\x12\f\n" +
	"\x01v\x18\x01 \x01(\tR\x01v\x12\x1b\n" +
	"\tdata_json\x18\x02 \x01(\fR\bdataJson\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x03 \x01(\x03R\ttimeoutMs\"a\n" +
	"\x0eInvokeResponse\x12\f\n" +
	"\x01v\x18\x01 \x01(\tR\x01v\x12\x0e\n" +
	"\x02ok\x18\x02 \x01(\bR\x02ok\x12\x1b\n" +
	"\tdata_json\x18\x03 \x01(\fR\bdataJson\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error2\xdd\x05\n" +
	"\tConnector\x12c\n" +
	"\rGetDefinition\x12!.squadaegis.connectorrpc.v1.Empty\x1a/.squadaegis.connectorrpc.v1.ConnectorDefinition\x12^\n" +
	"\n" +
	"Initialize\x12-.squadaegis.connectorrpc.v1.InitializeRequest\x1a!.squadaegis.connectorrpc.v1.Empty\x12M\n" +
	"\x05Start\x12!.squadaegis.connectorrpc.v1.Empty\x1a!.squadaegis.connectorrpc.v1.Empty\x12L\n" +
	"\x04Stop\x12!.squadaegis.connectorrpc.v1.Empty\x1a!.squadaegis.connectorrpc.v1.Empty\x12Z\n" +
	"\tGetStatus\x12!.squadaegis.connectorrpc.v1.Empty\x1a*.squadaegis.connectorrpc.v1.StatusResponse\x12V\n" +
	"\tGetConfig\x12!.squadaegis.connectorrpc.v1.Empty\x1a&.squadaegis.connectorrpc.v1.ConfigJSON\x12Y\n" +
	"\fUpdateConfig\x12&.squadaegis.connectorrpc.v1.ConfigJSON\x1a!.squadaegis.connectorrpc.v1.Empty\x12_\n" +
	"\x06Invoke\x12).squadaegis.connectorrpc.v1.InvokeRequest\x1a*.squadaegis.connectorrpc.v1.InvokeResponseBEZCgo.codycody31.dev/squad-aegis/pkg/connectorrpc/proto;connectorrpcpbb\x06proto3"

var (
	file_pkg_connectorrpc_proto_connector_proto_rawDescOnce sync.Once
	file_pkg_connectorrpc_proto_connector_proto_rawDescData []byte
)

func file_pkg_connectorrpc_proto_connector_proto_rawDescGZIP() []byte {
	file_pkg_connectorrpc_proto_connector_proto_rawDescOnce.Do(func() {
		file_pkg_connectorrpc_proto_connector_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_connectorrpc_proto_connector_proto_rawDesc), len(file_pkg_connectorrpc_proto_connector_proto_rawDesc)))
	})
	return file_pkg_connectorrpc_proto_connector_proto_rawDescData
}

var file_pkg_connectorrpc_proto_connector_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_pkg_connectorrpc_proto_connector_proto_goTypes = []any{
	(*Empty)(nil),               // 0: squadaegis.connectorrpc.v1.Empty
	(*ConfigField)(nil),         // 1: squadaegis.connectorrpc.v1.ConfigField
	(*ConfigSchema)(nil),        // 2: squadaegis.connectorrpc.v1.ConfigSchema
	(*ConnectorDefinition)(nil), // 3: squadaegis.connectorrpc.v1.ConnectorDefinition
	(*InitializeRequest)(nil),   // 4: squadaegis.connectorrpc.v1.InitializeRequest
	(*StatusResponse)(nil),      // 5: squadaegis.connectorrpc.v1.StatusResponse
	(*ConfigJSON)(nil),          // 6: squadaegis.connectorrpc.v1.ConfigJSON
	(*InvokeRequest)(nil),       // 7: squadaegis.connectorrpc.v1.InvokeRequest
	(*InvokeResponse)(nil),      // 8: squadaegis.connectorrpc.v1.InvokeResponse
}
var file_pkg_connectorrpc_proto_connector_proto_depIdxs = []int32{
	1,  // 0: squadaegis.connectorrpc.v1.ConfigField.nested:type_name -> squadaegis.connectorrpc.v1.ConfigField
	1,  // 1: squadaegis.connectorrpc.v1.ConfigSchema.fields:type_name -> squadaegis.connectorrpc.v1.ConfigField
	2,  // 2: squadaegis.connectorrpc.v1.ConnectorDefinition.config_schema:type_name -> squadaegis.connectorrpc.v1.ConfigSchema
	0,  // 3: squadaegis.connectorrpc.v1.Connector.GetDefinition:input_type -> squadaegis.connectorrpc.v1.Empty
	4,  // 4: squadaegis.connectorrpc.v1.Connector.Initialize:input_type -> squadaegis.connectorrpc.v1.InitializeRequest
	0,  // 5: squadaegis.connectorrpc.v1.Connector.Start:input_type -> squadaegis.connectorrpc.v1.Empty
	0,  // 6: squadaegis.connectorrpc.v1.Connector.Stop:input_type -> squadaegis.connectorrpc.v1.Empty
	0,  // 7: squadaegis.connectorrpc.v1.Connector.GetStatus:input_type -> squadaegis.connectorrpc.v1.Empty
	0,  // 8: squadaegis.connectorrpc.v1.Connector.GetConfig:input_type -> squadaegis.connectorrpc.v1.Empty
	6,  // 9: squadaegis.connectorrpc.v1.Connector.UpdateConfig:input_type -> squadaegis.connectorrpc.v1.ConfigJSON
	7,  // 10: squadaegis.connectorrpc.v1.Connector.Invoke:input_type -> squadaegis.connectorrpc.v1.InvokeRequest
	3,  // 11: squadaegis.connectorrpc.v1.Connector.GetDefinition:output_type -> squadaegis.connectorrpc.v1.ConnectorDefinition
	0,  // 12: squadaegis.connectorrpc.v1.Connector.Initialize:output_type -> squadaegis.connectorrpc.v1.Empty
	0,  // 13: squadaegis.connectorrpc.v1.Connector.Start:output_type -> squadaegis.connectorrpc.v1.Empty
	0,  // 14: squadaegis.connectorrpc.v1.Connector.Stop:output_type -> squadaegis.connectorrpc.v1.Empty
	5,  // 15: squadaegis.connectorrpc.v1.Connector.GetStatus:output_type -> squadaegis.connectorrpc.v1.StatusResponse
	6,  // 16: squadaegis.connectorrpc.v1.Connector.GetConfig:output_type -> squadaegis.connectorrpc.v1.ConfigJSON
	0,  // 17: squadaegis.connectorrpc.v1.Connector.UpdateConfig:output_type -> squadaegis.connectorrpc.v1.Empty
	8,  // 18: squadaegis.connectorrpc.v1.Connector.Invoke:output_type -> squadaegis.connectorrpc.v1.InvokeResponse
	11, // [11:19] is the sub-list for method output_type
	3,  // [3:11] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_pkg_connectorrpc_proto_connector_proto_init() }
func file_pkg_connectorrpc_proto_connector_proto_init() {
	if File_pkg_connectorrpc_proto_connector_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_connectorrpc_proto_connector_proto_rawDesc), len(file_pkg_connectorrpc_proto_connector_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_connectorrpc_proto_connector_proto_goTypes,
		DependencyIndexes: file_pkg_connectorrpc_proto_connector_proto_depIdxs,
		MessageInfos:      file_pkg_connectorrpc_proto_connector_proto_msgTypes,
	}.Build()
	File_pkg_connectorrpc_proto_connector_proto = out.File
	file_pkg_connectorrpc_proto_connector_proto_goTypes = nil
	file_pkg_connectorrpc_proto_connector_proto_depIdxs = nil
}
