steps:
  release-helper:
    image: woodpeckerci/plugin-ready-release-go:3.1.3
    pull: true
    settings:
      release_branch: ${CI_REPO_DEFAULT_BRANCH}
      git_email: me@codycody31.dev
      forge_token:
        from_secret: github_token

when:
  - event: push
    branch: ${CI_REPO_DEFAULT_BRANCH}
  - event: manual
    evaluate: 'TASK == "release-helper"'
